/**
 * Advisor co-pilot tip — ADR-316. A periodic, consent-gated, budget-capped
 * suggestion generated by ruflo's existing Fable Advisor Harness
 * (services/fable-harness.ts, ADR-172), surfaced in the local insight
 * ticker (insights.ts) alongside the CVE/uncommitted/power-saver signals.
 *
 * This is the ONE insight source that spends real money and makes a real
 * network call — every other source in insights.ts is synchronous, local,
 * $0 by construction. Three hard gates keep that safe:
 *   1. consent: 'advisor-tips' domain (types.ts/consent.ts), never bundled
 *      with anything else, off by default.
 *   2. cooldown: at most once per ADVISOR_REFRESH_TTL_MS regardless of how
 *      many sessions run in that window — a file-based TTL checked BEFORE
 *      spawning, not a per-call budget hope.
 *   3. budget: FableHarness's own --max-budget-usd hard cap, passed through
 *      to the underlying `claude -p` call.
 *
 * The snapshot sent to the model is built ONLY from the same structural
 * signals insights.ts already uses (funnel/local-signals.ts) — never raw
 * prompts, commands, or file contents. Matches ADR-309's "no raw content,
 * ever" bar even though ADR-309 is about telemetry and this is a different,
 * separately-consented data flow (an opt-in advisor query, not analytics).
 *
 * Cheapness/latency discipline for the CALLER (never this module itself):
 * refreshAdvisorTipIfStale performs a real network-bound `claude -p` spawn
 * when stale — callers MUST run it from a properly-awaited, DETACHED
 * background process (mirroring the funnel-cache fix's
 * spawnDetachedFunnelRefresh pattern), never inline in a statusline render.
 */

import { hasConsent } from './consent.js';
import { readStateJson, writeStateJson } from './state.js';
import { FableHarness, type CoPilotSnapshot } from '../services/fable-harness.js';

const ADVISOR_CACHE_FILE = 'advisor-tip.json';
/** At most one real spend per real day, regardless of session count. */
export const ADVISOR_REFRESH_TTL_MS = 24 * 60 * 60 * 1000;
/** Conservative default — one adviseCoPilotTip call is a single, unbatched
 * item, so the ~$0.34 clean-cwd anchor (not the $0.02 batched anchor)
 * applies. Override via RUFLO_ADVISOR_MAX_BUDGET_USD for advanced users. */
export const ADVISOR_DEFAULT_BUDGET_USD = 0.4;

interface AdvisorTipCache {
  _ts: number;
  headline?: string;
  detail?: string;
}

export interface CachedAdvisorTip {
  headline: string;
  detail: string;
}

/** Synchronous, $0, no network — safe to call from the insight ticker's hot path. */
export function readAdvisorTip(now: Date = new Date()): CachedAdvisorTip | null {
  const cache = readStateJson<AdvisorTipCache>(ADVISOR_CACHE_FILE);
  // `!cache._ts` would wrongly treat a legitimate epoch-zero timestamp as
  // absent (0 is falsy) — check the type explicitly instead.
  if (!cache || !cache.headline || typeof cache._ts !== 'number') return null;
  if (now.getTime() - cache._ts >= ADVISOR_REFRESH_TTL_MS) return null;
  return { headline: cache.headline, detail: cache.detail ?? '' };
}

function isCacheStale(now: Date): boolean {
  const cache = readStateJson<AdvisorTipCache>(ADVISOR_CACHE_FILE);
  if (!cache || typeof cache._ts !== 'number') return true;
  return now.getTime() - cache._ts >= ADVISOR_REFRESH_TTL_MS;
}

function resolveBudgetUsd(): number {
  const raw = process.env.RUFLO_ADVISOR_MAX_BUDGET_USD;
  const n = raw !== undefined ? Number(raw) : NaN;
  return Number.isFinite(n) && n > 0 ? n : ADVISOR_DEFAULT_BUDGET_USD;
}

export interface AdvisorRefreshResult {
  refreshed: boolean;
  reason?: 'not-consented' | 'fresh' | 'no-tip' | 'error';
}

/**
 * Refresh the cached advisor tip if consent is granted AND the cache is
 * stale. Spends real money via FableHarness exactly once per call site,
 * gated by the TTL check above — callers get to decide cadence (e.g.
 * "call this on every session-restore"; the TTL makes repeated calls cheap
 * no-ops within the same window).
 */
export async function refreshAdvisorTipIfStale(
  snapshot: CoPilotSnapshot,
  opts: { now?: Date; harness?: FableHarness } = {},
): Promise<AdvisorRefreshResult> {
  const now = opts.now ?? new Date();
  if (!hasConsent('advisor-tips')) return { refreshed: false, reason: 'not-consented' };
  if (!isCacheStale(now)) return { refreshed: false, reason: 'fresh' };

  const harness = opts.harness ?? new FableHarness({ maxBudgetUsd: resolveBudgetUsd() });
  try {
    const tip = await harness.adviseCoPilotTip(snapshot);
    if (!tip) {
      // The model looked and found nothing worth surfacing — still stamp
      // _ts so we don't re-spend inside the same TTL window re-asking the
      // same question and getting the same "nothing to say" answer.
      writeStateJson(ADVISOR_CACHE_FILE, { _ts: now.getTime() });
      return { refreshed: true, reason: 'no-tip' };
    }
    writeStateJson(ADVISOR_CACHE_FILE, { _ts: now.getTime(), headline: tip.headline, detail: tip.detail });
    return { refreshed: true };
  } catch {
    return { refreshed: false, reason: 'error' };
  }
}
