import {buildPlan,datePlus,planCSV,autolistCSV} from './plan.mjs';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
const BRANDS={
 purivelle:{name:'PURIVELLE',display:'Purivelle',domain:'purivelle.store',products:'products.json',heroTitle:'Der kleine Feierabend.',colors:{bg:'#e1e8d8',fg:'#19362d',paper:'#f7f7ef'},tag:'P U R I V E L L E'},
 deskrebel:{name:'DESKREBEL',display:'DeskRebel',domain:'deskrebel.store',products:'products-deskrebel.json',heroTitle:'Dein Körper. Dein Spielfeld.',colors:{bg:'#10141b',fg:'#f4f5f7',paper:'#ff6239'},tag:'D E S K R E B E L'}
};
const STORAGE='brand-studio-v2';
let brandId=$('brand').value||'purivelle',products=[],plan=[],selected=0,day=0,loadedImage=null,loadId=0,recording=false,recorder=null,frame=0,downloadURL=null,creatorClip=null,creatorClipUrl=null;
let saved={};try{saved=JSON.parse(localStorage.getItem(`${STORAGE}:${brandId}`)||'{}');}catch{}
const THEMES={sage:['#e1e8d8','#19362d','#f7f7ef'],night:['#142a25','#e1edb4','#233c31'],clay:['#eeddd0','#4b332c','#faf2e9']};
function feedback(s,error=false){$('feedback').textContent=s;$('feedback').classList.toggle('error',error);}
function persist(){try{localStorage.setItem(`${STORAGE}:${brandId}`,JSON.stringify({plan,start:$('startDate').value,mode:$('format').value,notes:$('notes').value}));}catch{feedback('Der Browser konnte die Änderungen nicht speichern. Bitte als Datei sichern.',true);}}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function textLines(text,x,y,width,size,lineHeight,max=4,font='Arial'){ctx.font=`${size}px ${font}`;let lines=[],line='';for(const word of String(text).split(/\s+/)){const test=line?line+' '+word:word;if(ctx.measureText(test).width>width&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);lines.slice(0,max).forEach((s,i)=>ctx.fillText(i===max-1&&lines.length>max?s+'…':s,x,y+i*lineHeight));}
function cover(img,x,y,w,h,zoom=1){const scale=Math.max(w/img.videoWidth||w/img.naturalWidth,h/img.videoHeight||h/img.naturalHeight)*zoom;const iw=(img.videoWidth||img.naturalWidth)*scale,ih=(img.videoHeight||img.naturalHeight)*scale;ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);}
function drawSubtitle(text,y,accent){ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=24;ctx.fillStyle='#f8f5ed';ctx.beginPath();ctx.roundRect(35,y-78,650,126,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#151515';ctx.textAlign='center';ctx.font='900 43px Arial Narrow,Impact,Arial';let s=String(text||'').trim();while(ctx.measureText(s).width>610&&s.length>8)s=s.slice(0,-2).trim();ctx.fillText(s,360,y,610);ctx.fillStyle=accent;ctx.fillRect(55,y+31,610,5);ctx.restore();}
function render(t=0,duration=0){
 const profile=BRANDS[brandId],desk=brandId==='deskrebel';const [themeBg,themeFg,themePaper]=THEMES[$('theme').value]||THEMES.sage;const bg=desk?profile.colors.bg:themeBg,fg=desk?profile.colors.fg:themeFg,paper=desk?'#f5f5f2':themePaper,accent=desk?profile.colors.paper:fg;
 const product=products.find(x=>x.id===$('product').value);const seconds=duration||12,stage=Math.min(2,Math.floor(Math.max(0,t)/Math.max(1,seconds/3)));ctx.fillStyle=bg;ctx.fillRect(0,0,720,1280);
 if(creatorClip&&creatorClip.readyState>=2&&stage!==1){cover(creatorClip,0,0,720,1280,1.025+Math.sin(t*.12)*.015);ctx.fillStyle='#0004';ctx.fillRect(0,0,720,1280);}
 else if(loadedImage){ctx.fillStyle=bg;ctx.fillRect(0,0,720,1280);if(stage===1){const zoom=1.025+Math.sin(t*.13)*.02;cover(loadedImage,45,145,630,850,zoom);ctx.fillStyle=fg;ctx.font='18px Arial';ctx.fillText(profile.name,50,75);ctx.fillText(product?.title||'',50,1085);}}
 ctx.fillStyle=accent;ctx.fillRect(0,0,720,12);ctx.fillStyle=fg;ctx.font='bold 20px Arial';ctx.fillText(profile.name,48,66);ctx.font='13px Arial';ctx.textAlign='right';ctx.fillText('12s STORY',672,66);ctx.textAlign='left';
 if(stage!==1){const line=stage===0?$('headline').value:(product?.name||$('subline').value);drawSubtitle(line,1010,accent);}else{ctx.fillStyle=paper;ctx.beginPath();ctx.roundRect(35,1080,650,102,8);ctx.fill();ctx.fillStyle=desk?'#141820':'#19362d';ctx.font='bold 24px Arial';textLines(product?.title||'',58,1122,600,24,29,2);}
 if(stage===2){ctx.fillStyle=accent;ctx.font='bold 18px Arial';ctx.fillText('JETZT ENTDECKEN',48,1195);ctx.textAlign='right';ctx.fillText(profile.domain,672,1195);ctx.textAlign='left';}
 if(duration){ctx.fillStyle=fg;ctx.fillRect(0,1270,720*Math.min(1,t/duration),10);}
}
async function loadProduct(){const token=++loadId;loadedImage=null;render();const p=products.find(x=>x.id===$('product').value);if(!p)return;try{const img=new Image();img.crossOrigin='anonymous';img.src=p.image;await img.decode();if(token!==loadId)return;loadedImage=img;render();}catch{if(token===loadId)feedback('Produktbild konnte nicht geladen werden. Internetverbindung prüfen oder ein anderes Produkt wählen.',true);}}
function applySelected(){const p=plan[selected];if(!p)return;$('product').value=p.productId;$('headline').value=p.headline;$('subline').value=p.subline;$('caption').value=p.caption;loadProduct();}
function saveEdit(){const p=plan[selected];if(!p)return;Object.assign(p,{productId:$('product').value,headline:$('headline').value,subline:$('subline').value,caption:$('caption').value});persist();showCards();}
function showCards(){const host=$('cards');host.replaceChildren();plan.forEach((p,index)=>{if(p.day!==day)return;const product=products.find(x=>x.id===p.productId);const button=document.createElement('button');button.className='card';button.type='button';const img=document.createElement('img');img.src=product.image;img.alt=product.title;img.loading='lazy';const body=document.createElement('div');body.className='card-body';const time=document.createElement('time');time.textContent=p.time+' · '+p.series;const h=document.createElement('h3');h.textContent=p.headline;const tag=document.createElement('span');tag.className='tag';tag.textContent=(p.type==='video'?'VIDEOIDEE':'BILDBEITRAG')+' / ENTWURF';body.append(time,h,tag);button.append(img,body);button.onclick=()=>{if(recording)return;saveEdit();selected=index;applySelected();$('editor').scrollIntoView({behavior:'smooth'});};host.append(button);});}
function showDays(){const host=$('days');host.replaceChildren();for(let i=0;i<7;i++){const b=document.createElement('button');b.type='button';b.textContent=new Date(datePlus($('startDate').value,i)+'T12:00:00Z').toLocaleDateString('de-DE',{weekday:'short',day:'numeric',month:'numeric',timeZone:'Europe/Berlin'});b.className=i===day?'selected':'';b.setAttribute('aria-pressed',i===day?'true':'false');b.onclick=()=>{day=i;showDays();showCards();};host.append(b);}showCards();}
function setBusy(b){recording=b;document.querySelectorAll('#editorForm input,#editorForm select,#editorForm textarea,#editorForm button,#newPlan,#format,#startDate,#cards button').forEach(el=>el.disabled=b);$('cancel').disabled=false;$('cancel').hidden=!b;$('progress').hidden=!b;}
async function exportVideo(){
 if(!creatorClip)return feedback('Lade zuerst einen Creator-Clip mit Produktaufnahme hoch. Ohne echtes Footage exportiere ich kein billiges Standbildvideo.',true);
 if(!loadedImage)return feedback('Das Produktbild muss zuerst vollständig geladen sein.',true);
 if(!window.MediaRecorder||!canvas.captureStream)return feedback('Dieser Browser unterstützt den Video-Export nicht. Bitte einen aktuellen Chrome- oder Edge-Browser verwenden.',true);
 saveEdit();const duration=Number($('duration').value);const mime=['video/mp4;codecs=avc1.42E01E','video/webm;codecs=vp8','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)return feedback('Kein unterstütztes Videoformat im Browser gefunden.',true);
 let stream,aborted=false,wake=null,chunks=[];setBusy(true);$('videoResult').replaceChildren();$('progress').value=0;
 try{if(navigator.wakeLock)try{wake=await navigator.wakeLock.request('screen');}catch{}
 render(0,duration);stream=canvas.captureStream(30);if(creatorClip.captureStream){try{const sourceStream=creatorClip.captureStream();for(const track of sourceStream.getAudioTracks())stream.addTrack(track);}catch{}}recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});
 const done=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||new Error('Exportfehler'));});
 const cancel=()=>{aborted=true;if(recorder?.state==='recording')recorder.stop();};$('cancel').onclick=cancel;
 const visibility=()=>{if(document.hidden)cancel();};document.addEventListener('visibilitychange',visibility);
 creatorClip.currentTime=0;creatorClip.loop=true;await creatorClip.play();const start=performance.now();recorder.start(500);feedback(`Export läuft (${duration} Sekunden). Bitte diesen Tab sichtbar lassen.`);
 const tick=()=>{if(recorder.state!=='recording')return;const t=(performance.now()-start)/1000;render(Math.min(t,duration),duration);$('progress').value=Math.min(100,t/duration*100);if(t>=duration)recorder.stop();else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
 try{await done;}finally{document.removeEventListener('visibilitychange',visibility);}
 if(aborted){feedback('Export abgebrochen. Bei einem Tabwechsel wird gestoppt, damit kein unvollständiges Video als fertig erscheint.');return;}
 if(downloadURL)URL.revokeObjectURL(downloadURL);const blob=new Blob(chunks,{type:mime});downloadURL=URL.createObjectURL(blob);const video=document.createElement('video');video.src=downloadURL;video.controls=true;const a=document.createElement('a');a.href=downloadURL;a.download=`${brandId}-${duration}s.${mime.includes('mp4')?'mp4':'webm'}`;a.className='button primary';a.textContent='Fertiges Video herunterladen ↓';$('videoResult').append(video,a);feedback('Video fertig. '+(mime.includes('mp4')?'MP4-Export bereit.':'WebM-Export bereit; vor einem Metricool-Upload gegebenenfalls in MP4 umwandeln.'));
 }catch(e){feedback('Video konnte nicht exportiert werden: '+e.message,true);}finally{cancelAnimationFrame(frame);creatorClip?.pause();stream?.getTracks().forEach(t=>t.stop());if(wake)await wake.release().catch(()=>{});recorder=null;setBusy(false);render();}
}
async function loadBrand(nextBrand){
 if(!BRANDS[nextBrand])return;brandId=nextBrand;$('brand').value=brandId;const profile=BRANDS[brandId];
 try{saved=JSON.parse(localStorage.getItem(`${STORAGE}:${brandId}`)||'{}');}catch{saved={};}
 const response=await fetch(profile.products);if(!response.ok)throw new Error(`${profile.name}: Produktdaten konnten nicht geladen werden.`);products=await response.json();
 $('workspaceTitle').textContent=`${profile.name} / WORKSPACE`;$('brandName').textContent=profile.display;$('brandMark').textContent=brandId==='deskrebel'?'DR':'p.';$('campaignTitle').textContent=profile.heroTitle;$('footerBrand').textContent=profile.display;document.title=`${profile.display} — Community Studio`;$('product').replaceChildren();
 for(const p of products){const option=document.createElement('option');option.value=p.id;option.textContent=p.title;$('product').append(option);}
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('startDate').value=saved.start||datePlus(today,1);$('format').value=['mix','bild','video'].includes(saved.mode)?saved.mode:'mix';
 plan=Array.isArray(saved.plan)&&saved.plan.length===35&&saved.plan.every(x=>products.some(p=>p.id===x.productId))?saved.plan:buildPlan(products,$('startDate').value,$('format').value,brandId);day=0;selected=0;
 $('notes').value=saved.notes||'';$('heroImage').src=products[0].image;$('notes').oninput=persist;showDays();applySelected();render();
 try{const status=await fetch('publishing-status.json',{cache:'no-store'});if(!status.ok)throw new Error();const state=await status.json();$('scheduledCount').textContent=String(state.scheduled||0);$('scheduleStatus').textContent=`${state.message} Metricool: Nur ${state.metricoolBrand||'futureflowxx'} ist verbunden; verbinde zuerst ein eigenes ${profile.name}-Profil.`;}catch{$('scheduledCount').textContent='0';$('scheduleStatus').textContent=`${profile.name}: Entwürfe bereit. Automatisches Posting ist nicht aktiv.`;}
 persist();
}
async function init(){
 await loadBrand(brandId);$('brand').onchange=()=>{saveEdit();loadBrand($('brand').value).catch(e=>feedback(e.message,true));};
 $('newPlan').onclick=()=>{try{const next=buildPlan(products,$('startDate').value,$('format').value,brandId);plan=next;selected=0;day=0;persist();showDays();applySelected();feedback('Neuer Wochenplan erstellt.');}catch(e){feedback(e.message,true);}};
 $('editorForm').onsubmit=e=>e.preventDefault();$('product').onchange=loadProduct;['headline','subline','theme'].forEach(id=>$(id).addEventListener('input',()=>render()));
 $('save').onclick=()=>{saveEdit();feedback('Entwurf in diesem Browser gespeichert.');};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('caption').value);feedback('Beitragstext kopiert.');}catch{feedback('Kopieren nicht verfügbar. Text im Feld markieren und kopieren.',true);}};
 $('png').onclick=()=>{if(!loadedImage)return feedback('Bitte warten, bis das Produktbild geladen ist.',true);render();try{canvas.toBlob(b=>{if(b){download(b,`${brandId}-beitrag.png`);feedback('Bild-Download gestartet.');}else feedback('Bild konnte nicht exportiert werden.',true);},'image/png');}catch{feedback('Bildexport vom Browser blockiert.',true);}};
 $('video').onclick=exportVideo;$('downloadPlan').onclick=()=>{saveEdit();download(new Blob([planCSV(plan,products)],{type:'text/csv;charset=utf-8'}),`${brandId}-wochenplan.csv`);};
 const auto=document.createElement('button');auto.className='text-button';auto.textContent='Bilder für Metricool-Autoliste ↓';auto.onclick=()=>{saveEdit();const images=plan.filter(x=>x.type==='bild');if(!images.length)return feedback('Der Plan enthält nur Videoideen. Wähle zuerst Bilder oder einen Mix.',true);download(new Blob([autolistCSV(plan,products)],{type:'text/csv;charset=utf-8'}),`${brandId}-metricool-autoliste.csv`);feedback(`${images.length} Bildbeiträge exportiert. In Metricool unter Autolisten importieren; Kanal und Zeitplan dort festlegen. Der Import veröffentlicht noch nichts aus dieser App.`);};document.querySelector('.toolbar').append(auto);
 $('sourceVideo').onchange=event=>{const file=event.target.files?.[0];if(!file)return;if(creatorClipUrl)URL.revokeObjectURL(creatorClipUrl);creatorClipUrl=URL.createObjectURL(file);creatorClip=document.createElement('video');creatorClip.src=creatorClipUrl;creatorClip.preload='auto';creatorClip.playsInline=true;creatorClip.crossOrigin='anonymous';creatorClip.onloadeddata=()=>{render();feedback(`Creator-Clip bereit (${creatorClip.duration.toFixed(1)} s). Exportiert werden die ersten ${$('duration').value} Sekunden.`);};creatorClip.onerror=()=>feedback('Creator-Clip konnte nicht geladen werden. Bitte MP4 oder WebM verwenden.',true);};
 $('backup').onclick=()=>{saveEdit();download(new Blob([JSON.stringify({plan,notes:$('notes').value},null,2)],{type:'application/json'}),'purivelle-studio-backup.json');};
 showDays();applySelected();
 try{const res=await fetch('publishing-status.json',{cache:'no-store'});if(!res.ok)throw new Error();const status=await res.json();$('scheduledCount').textContent=String(status.scheduled||0);$('scheduleStatus').textContent=status.message;}catch{$('scheduleStatus').textContent='Veröffentlichungsstatus nicht abrufbar. Die 35 Beiträge sind lokale Entwürfe; automatisches Posting ist nicht aktiv.';}
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
init().catch(e=>{feedback(e.message,true);$('scheduleStatus').textContent='Studio konnte nicht vollständig geladen werden. Bitte Seite neu laden.';});
