// Individually authored AI copy, grounded in the existing product catalog.
// No claims of live language-model inference or invented product specifications.
export const creatives = {
 '11638691529045': ['Dein Feierabend. Ein kleines Ritual.', 'LotusTap ist ein Massagehammer für deine persönliche Auszeit. Entdecke das Produkt und seine Anwendung im Shop.', 'On a warm neutral table, an adult hand picks up the exact massage hammer from the reference image and slowly turns it to show its head and handle. Soft evening window light, relaxed everyday setting.', 'Ein kleiner Moment, der nur dir gehört. Entdecke LotusTap von Purivelle.'],
 '11638660890965': ['Ein Detail für deinen Alltag.', 'BackEase verbindet eine Rückenstütze mit einem atmungsaktiven Gurt. Schau dir Form, Details und Anwendung in Ruhe an.', 'An adult creator holds the exact back support belt from the reference in front of a light shirt. Close-up of the fabric and fastening, then a gentle turn of the belt. Warm daylight, no before-and-after comparison.', 'BackEase im Detail: Schau dir deine nächste Alltagsbegleitung an.'],
 '11638660104533': ['Eine Pause für deine Hände.', 'FingerFlow ist ein Holz-Massageroller für Finger und Hand. Ein kleines Produkt für dein bewusstes Alltagsritual.', 'Close-up of adult hands on a clean wooden desk. One hand slowly turns the exact wooden finger massage roller from the reference. Reveal its rollers with a subtle camera push-in and warm natural light.', 'Zwischen zwei Aufgaben kurz innehalten. FingerFlow entdecken.'],
 '11638225305941': ['Klein im Format. Ganz dein Moment.', 'ThumbPoint ist ein kompaktes, manuelles Massagegerät für dein persönliches Ritual. Die Produktseite zeigt dir die Details.', 'An adult hand holds the exact compact thumb-shaped massage tool from the reference. Slowly rotate it above a cream linen surface to show its shape. Intimate smartphone product close-up, soft shadows.', 'Dein kleines Ritual mit ThumbPoint. Jetzt bei Purivelle ansehen.'],
 '11627845255509': ['Nach dem Training kurz ankommen.', 'DeepStick ist ein Massagestab für deine persönliche Routine. Entdecke seine Form und Verarbeitung in der Detailansicht.', 'The exact massage stick from the reference rests beside a folded exercise mat. An adult hand picks it up by the handle and slowly turns it. Close-up of its surface, warm evening light, natural camera movement.', 'Was gehört zu deiner Routine nach dem Training? DeepStick entdecken.'],
 '11627844272469': ['Mach Platz für deine Pause.', 'TapRelax ist ein Silikon-Klopfpaddel zur Selbstmassage. Ein bewusst gewähltes Detail für deine persönliche Auszeit.', 'On a cozy neutral sofa, an adult hand lifts the exact silicone massage paddle from the reference and shows its surface to the camera. Slow natural movement, tactile detail, soft daylight.', 'Eine kleine Pause im Alltag. TapRelax von Purivelle.'],
 '11627843551573': ['Deine Matte. Dein Moment.', 'RelaxRoll ist eine Faszienrolle aus EPP-Hartschaum. Sie ergänzt deine persönliche Bewegungsroutine.', 'The exact foam roller from the reference sits on a clean exercise mat. An adult hand rolls it a short distance forward and back. Low camera angle, realistic textured foam, gentle daylight.', 'Deine Bewegungsroutine beginnt bei dir. RelaxRoll entdecken.'],
 '11627838177621': ['Ein ruhiger Moment für dich.', 'WarmEase ist eine Nackenbandage. Entdecke Material, Form und die Hinweise zur Anwendung auf der Produktseite.', 'An adult hand unfolds the exact neck wrap from the reference on a neutral fabric surface. Close-up of the closure and shape, then a slow camera move along the material. No heat effects, no medical imagery.', 'WarmEase im Detail. Nimm dir Zeit für deine persönliche Routine.'],
 '11627824906581': ['Weniger Hektik. Mehr Zeit für dich.', 'SculptRoll ist ein Massageroller für deine Körperpflege-Routine. Entdecke das Produkt aus verschiedenen Perspektiven.', 'An adult hand gently rotates the exact body massage roller from the reference on a light tabletop. Close-up of the rolling elements and handles. Natural skin texture, warm soft window light.', 'Deine Routine, dein Tempo. SculptRoll von Purivelle entdecken.'],
 '11627822186837': ['Eine kleine Kugel für deine Routine.', 'PointFlow ist ein Silikon-Faszienball. Sein kompaktes Format passt zu deinem persönlichen Bewegungsritual.', 'The exact silicone massage ball from the reference sits next to a folded mat. An adult hand gently rolls it across the palm, preserving the original surface and color. Macro product detail, calm daylight.', 'Welches kleine Ritual gehört zu deinem Tag? PointFlow entdecken.'],
 'desk-armforce': ['Dein Training beginnt hier.', 'ArmForce ist ein Power-Twister für deine Trainingsroutine. Entdecke das Produkt und die Anwendungshinweise bei DeskRebel.', 'The exact power twister from the reference rests on a dark exercise mat. An adult hand lifts it by its handles without bending it, revealing its construction. Side window light, crisp realistic texture.', 'Bereit für deine nächste Session? ArmForce bei DeskRebel entdecken.'],
 'desk-doorkit': ['Ein kleines Set. Deine nächste Session.', 'DoorKit kombiniert Türanker, Griffe und Karabiner. Schau dir die Bestandteile und Hinweise zur sicheren Verwendung im Shop an.', 'On a dark neutral surface, an adult hand lays out the exact door anchor kit pieces shown in the reference. Show the handles and carabiners in a careful close-up. Do not add any extra components.', 'Dein Setup im Detail. DoorKit von DeskRebel.'],
 'desk-elbowguard': ['Ein Detail in deinem Trainingssetup.', 'ElbowGuard ist eine Kompressions-Ellbogenbandage. Entdecke Material, Passformangaben und verfügbare Varianten im Shop.', 'An adult creator holds the exact elbow sleeve from the reference against a neutral shirt. Slow close-up of the fabric and seams, then a gentle turn. Bright realistic gym corner, no injury or recovery imagery.', 'ElbowGuard entdecken. Dein Training, dein Setup.'],
 'desk-flexloop': ['Eine neue Bewegung für deinen Tag.', 'FlexLoop ist ein breites Widerstandsband für deine Trainingsroutine. Entdecke die verfügbaren Varianten im Shop.', 'The exact wide resistance band from the reference lies beside an exercise mat. Adult hands pick it up and unfold it gently without overstretching. Close-up of material, realistic daylight, subtle handheld camera.', 'FlexLoop von DeskRebel. Mach deine nächste Session zu deiner.'],
 'desk-gripring': ['Klein genug für deine Trainingspause.', 'GripRing ist ein Silikon-Handtrainer. Ein kompaktes Trainingsdetail für deine persönliche Routine.', 'An adult hand gently squeezes and releases the exact silicone grip ring from the reference once. Close-up at a clean desk, natural daylight, realistic finger motion. Preserve the ring shape, color and surface.', 'Eine kurze Pause, ein kleiner Handgriff. GripRing von DeskRebel entdecken.'],
 'desk-jumprebel': ['Zeit, in Bewegung zu kommen.', 'JumpRebel ist ein Speed-Springseil mit Kugellager. Entdecke Griffe und Details für deine nächste Trainingssession.', 'The exact speed jump rope from the reference is neatly coiled on a dark floor. An adult hand picks up one handle and rotates it slowly to reveal its details. Athletic natural light, no invented display or electronics.', 'Deine nächste Session wartet. JumpRebel von DeskRebel.'],
 'desk-lumbarease': ['Deine Pause nach dem Training.', 'LumbarEase ist ein Massagegurt für den unteren Rücken. Schau dir Form und Anwendungshinweise auf der Produktseite an.', 'An adult hand unfolds the exact lumbar massage belt from the reference on a neutral bench beside a towel. Reveal its handles and textured surface. Slow camera slide, soft window light, no medical claims.', 'LumbarEase im Detail. Entdecke deine persönliche Routine.'],
 'desk-oloop': ['Mehr Bewegung in deinem Alltag.', 'O-Loop ist ein Latex-Widerstandsring. Entdecke das kompakte Trainingsprodukt und seine Anwendungshinweise.', 'Adult hands gently lift the exact latex resistance ring from the reference above an exercise mat. Slowly turn it to show the complete shape. Keep its dimensions and material consistent; no dramatic stretching.', 'Deine Matte. Dein Tempo. O-Loop von DeskRebel.'],
 'desk-palmgrips': ['Der nächste Griff beginnt hier.', 'PalmGrips sind Silikon-Griffpads für dein Trainingssetup. Schau dir Form und Oberflächenstruktur im Detail an.', 'An adult hand picks up one of the exact silicone grip pads from the reference and turns it to show both sides. The matching pad stays visible on a dark bench. Realistic macro surface detail and side lighting.', 'PalmGrips entdecken. Ein Detail für dein Trainingssetup.'],
 'desk-pushpro': ['Dein Boden wird zum Trainingsplatz.', 'PushPro sind Liegestützgriffe in S-Form. Entdecke Form und Details für deine Trainingsroutine.', 'An adult places the exact pair of S-shaped push-up handles from the reference on an exercise mat. Close-up of both handles from a low angle, then a slow camera push-in. Preserve the exact construction, no extra parts.', 'PushPro von DeskRebel. Bereit für deine nächste Session?']
};
export function creativeFor(product, brand){
 const c=creatives[product.id];
 if(!c)return {headline:product.name||product.title,description:product.title,scene:'Slow realistic close-up of the exact product shown in the reference image. Preserve its appearance.',caption:product.title+' · '+brand,authored:false};
 return {headline:c[0],description:c[1],scene:c[2],caption:c[3],authored:true};
}
export function generationPrompt(product,creative,style='product'){
 const direction=style==='creator'?'A fictional adult product demonstrator in a natural everyday setting. No speaking or fabricated testimonial.':style==='detail'?'Premium macro product cinematography, subtle camera motion, tactile details.':'Realistic lifestyle product cinematography with a subtle handheld camera.';
 return `${creative.scene} ${direction} Use the provided image as the exact visual reference for ${product.title}. Preserve its design, colors, proportions and parts. Only plausible natural movement. No invented product features, before-and-after effects, logos, subtitles, or on-screen text.`;
}
