// NEULAND-Rechenmotor (motor-geld), unveraendert aus neuland/Gewinnspur.html herausgeloest -
// damit Zentrale (Browser) und GitHub Actions (Node) dieselbe Rechnung benutzen.
(() => {
'use strict';const T=window.NeulandTools||={};const MAX=1e12;
const obj=x=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Ein Objekt ist erforderlich.');return x;};
function num(x,label,{max=MAX,positive=false,integer=false,min=0}={}){if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>max||(positive&&x<=0)||(integer&&!Number.isInteger(x)))throw Error(label+': Endliche '+(integer?'ganze ':'')+'Zahl zwischen '+min+' und '+max+(positive?', größer als 0':'')+' erforderlich.');return x;}
const round=(x,p=2)=>x===null||!Number.isFinite(x)?null:Number(x.toFixed(p));const ratio=(a,b,f=1)=>b>0?round(a/b*f):null;const m=(label,value,unit='')=>({label,value,unit});
function orders(input,fields){obj(input);if(!Array.isArray(input.orders)||input.orders.length>100)throw Error('Aufträge: Liste mit höchstens 100 Einträgen erforderlich.');return input.orders.map(raw=>{obj(raw);if(typeof raw.product!=='string'||!raw.product.trim()||raw.product.length>200)throw Error('Produkt: Name mit 1 bis 200 Zeichen erforderlich.');const r={product:raw.product.trim()};fields.forEach(k=>r[k]=num(raw[k],k,{integer:k==='quantity',positive:k==='quantity'}));return r;});}
function flow(input){obj(input);return{cash:num(input.cash,'Geldbestand'),monthly_fixed_cost:num(input.monthly_fixed_cost,'Fixkosten'),monthly_revenue:num(input.monthly_revenue,'Umsatz'),variable_cost_rate:num(input.variable_cost_rate,'Variabler Kostenanteil',{max:1})};}
const cash={cash:6000,monthly_fixed_cost:2500,monthly_revenue:2000,variable_cost_rate:.25};
const labels={cash:'Geldbestand (€)',monthly_fixed_cost:'Monatliche Fixkosten (€)',monthly_revenue:'Monatlicher Umsatz (€)',variable_cost_rate:'Variabler Kostenanteil (0–1)',orders:'Aufträge',product:'Produkt',revenue:'Gesamter Auftragsumsatz (€)',cost:'Gesamte Auftragskosten (€)',fees:'Auftragsgebühren (€)',refund:'Auftragserstattungen (€)',quantity:'Stückzahl'};
const sample=[{product:'Werkzeugpaket',revenue:100,cost:30,fees:5,refund:10,quantity:2},{product:'Beratung',revenue:200,cost:100,fees:10,refund:0,quantity:1}];
const cashNotes=['Ein gemeinsamer Zeitraum; Umsatz wird als Zahlungseingang behandelt. Fixkosten und variabler Kostenanteil bleiben konstant.','Szenariorechnung: Zahlungstermine, Finanzierung und weitere Kosten sind nur enthalten, wenn sie erfasst wurden.','Ohne Geldabfluss gibt es keine endliche Reichweite. Unbekannt ist keine gemessene Null.'];
T.ProfitLeaks={name:'Gewinnspur',description:'Berechnet Deckungsbeiträge aus deinen Auftragssummen und zeigt Verlustaufträge.',labels,example:{orders:sample},run(input){const a=orders(input,['revenue','cost','fees','refund','quantity']);const sums={revenue:0,cost:0,fees:0,refund:0,quantity:0};let loss=0,negative=0;const products=new Map();a.forEach(x=>{Object.keys(sums).forEach(k=>sums[k]+=x[k]);const db=x.revenue-x.refund-x.cost-x.fees;if(db<0){negative++;loss-=db;}if(!products.has(x.product))products.set(x.product,{product:x.product,revenue:0,cost:0,fees:0,refund:0,quantity:0,count:0});const p=products.get(x.product);p.count++;Object.keys(sums).forEach(k=>p[k]+=x[k]);});const net=sums.revenue-sums.refund,db=net-sums.cost-sums.fees;const rows=[...products.values()].map(p=>({Produkt:p.product,Aufträge:p.count,Stückzahl:p.quantity,'Umsatz €':round(p.revenue),'Erstattung €':round(p.refund),'Kosten €':round(p.cost),'Gebühren €':round(p.fees),'Deckungsbeitrag €':round(p.revenue-p.refund-p.cost-p.fees),'Marge %':ratio(p.revenue-p.refund-p.cost-p.fees,p.revenue-p.refund,100)}));return{metrics:[m('Aufträge',a.length),m('Stückzahl',sums.quantity),m('Umsatz',round(sums.revenue),'EUR'),m('Nettoumsatz',round(net),'EUR'),m('Deckungsbeitrag',round(db),'EUR'),m('Gewichtete Marge',ratio(db,net,100),'%'),m('Verlustsumme negativer Aufträge',round(loss),'EUR'),m('Verlustaufträge',negative)],rows,notes:['Deckungsbeitrag = Umsatz − Erstattungen − Kosten − Gebühren. Stückzahlen multiplizieren keine Auftragssummen.','Marge aus Gesamtsummen, bei Nettoumsatz ≤ 0 nicht berechenbar. Fixkosten sind nicht separat enthalten.',...(a.some(x=>x.refund>x.revenue)?['Eine Erstattung übersteigt den Auftragsumsatz; Zuordnung prüfen.']:[]),...(!a.length?['Keine Aufträge: Summen der leeren Liste sind 0; kein Nachweis für ein Geschäft ohne Kosten.']:[])]};}};
T.RunwayRadar={name:'PufferPilot',description:'Vergleicht Geldabfluss und rechnerische Reichweite in drei Umsatzszenarien.',labels,example:cash,run(input){const x=flow(input);const rows=[.8,1,1.2].map(f=>{const revenue=x.monthly_revenue*f,change=revenue*(1-x.variable_cost_rate)-x.monthly_fixed_cost,burn=Math.max(0,-change);return{Szenario:f===1?'Basis':f===.8?'Umsatz −20 %':'Umsatz +20 %','Umsatz €/Monat':round(revenue),'Geldänderung €/Monat':round(change),'Abfluss €/Monat':round(burn),'Reichweite Monate':burn>0?ratio(x.cash,burn):null,'Geld nach 12 Monaten €':round(x.cash+12*change),Einordnung:burn>0?'Geldabfluss':'Kein laufender Geldabfluss im Modell'};});const b=rows[1];return{metrics:[m('Verfügbares Geld',x.cash,'EUR'),m('Geldänderung pro Monat',b['Geldänderung €/Monat'],'EUR'),m('Monatlicher Abfluss',b['Abfluss €/Monat'],'EUR'),m('Reichweite im Basismodell',b['Reichweite Monate'],'Monate'),m('Geld nach 12 Monaten',b['Geld nach 12 Monaten €'],'EUR')],rows,notes:cashNotes};}};
function fraction(n){const parts=String(n).toLowerCase().split('e'),exp=parts[1]?Number(parts[1]):0,point=parts[0].indexOf('.'),decimals=point<0?0:parts[0].length-point-1,digits=BigInt(parts[0].replace('.','')),power=exp-decimals;return power>=0?[digits*10n**BigInt(power),1n]:[digits,10n**BigInt(-power)];}
function whole(h,d){const[hn,hd]=fraction(h),[dn,dd]=fraction(d);return Number(hn*dd/(hd*dn));}
T.CapacityTwin={name:'Kapazitätszwilling',description:'Vergleicht verfügbare Arbeitszeit mit dem Zeitbedarf deiner Aufträge.',labels,example:{hours_available:80,hours_per_order:2,orders_expected:50},run(input){obj(input);const h=num(input.hours_available,'Verfügbare Stunden'),d=num(input.hours_per_order,'Stunden je Auftrag',{min:1e-9,positive:true}),q=num(input.orders_expected,'Aufträge',{integer:true}),capacity=whole(h,d),required=q*d;return{metrics:[m('Ganze Aufträge möglich',capacity),m('Benötigte Stunden',round(required),'h'),m('Freie Stunden',round(Math.max(0,h-required)),'h'),m('Fehlende Stunden',round(Math.max(0,required-h)),'h'),m('Fehlende Auftragskapazität',Math.max(0,q-capacity)),m('Auslastung',ratio(required,h,100),'%')],rows:[['Basis',h,d],['20 % mehr Zeit',h*1.2,d],['20 % weniger Zeit je Auftrag',h,d*.8]].map(([Szenario,Stunden,Zeit])=>({Szenario,Stunden:round(Stunden),'Stunden je Auftrag':round(Zeit,10),'Ganze Aufträge':whole(Stunden,Zeit),'Fehlende Auftragskapazität':Math.max(0,q-whole(Stunden,Zeit))})),notes:['Kapazität = verfügbare Stunden / Stunden je Auftrag, abgerundet. Auslastung = benötigte / verfügbare Stunden.','Gleichartige Aufträge und verfügbare Arbeitszeit angenommen. Material, Rüstzeiten und Qualifikationen fehlen.',...(capacity>Number.MAX_SAFE_INTEGER?['Extrem große Kapazität wird gerundet dargestellt; praktisch nutzbare Zeiteinheiten verwenden.']:[])]};}};
T.BreakEvenMap={name:'Schwellenkarte',description:'Berechnet den Monatsumsatz, der deine Fixkosten im Modell deckt.',labels,example:{monthly_fixed_cost:3000,monthly_revenue:5000,variable_cost_rate:.4},run(input){obj(input);const f=num(input.monthly_fixed_cost,'Fixkosten'),r=num(input.monthly_revenue,'Umsatz'),v=num(input.variable_cost_rate,'Variabler Kostenanteil',{max:1}),share=1-v,threshold=share>0?ratio(f,share):f===0?0:null;return{metrics:[m('Deckungsbeitragsanteil',round(share*100),'%'),m('Umsatzschwelle pro Monat',threshold,'EUR'),m('Abstand zur Schwelle',threshold===null?null:round(r-threshold),'EUR'),m('Modellüberschuss pro Monat',round(r*share-f),'EUR')],notes:['Umsatzschwelle = Fixkosten / (1 − variabler Kostenanteil).','Bei 100 % variablen Kosten und positiven Fixkosten gibt es keine endliche Schwelle; bei 0 Fixkosten beträgt sie 0 €.','Kostenrechnung, keine Umsatzprognose. Weitere Kosten müssen in den Eingaben enthalten sein.']};}};
T.ConcentrationWatch={name:'Abhängigkeitslupe',description:'Zeigt, wie stark sich erfasster Umsatz auf einzelne Produkte konzentriert.',labels,example:{orders:[{product:'Produkt A',revenue:75},{product:'Produkt B',revenue:25}]},run(input){const a=orders(input,['revenue']),p=new Map();let total=0;a.forEach(x=>{total+=x.revenue;p.set(x.product,(p.get(x.product)||0)+x.revenue);});const sorted=[...p].sort((a,b)=>b[1]-a[1]);return{metrics:[m('Produkte',p.size),m('Erfasster Umsatz',round(total),'EUR'),m('Größter Umsatzanteil',sorted.length?ratio(sorted[0][1],total,100):null,'%'),m('Konzentrationsindex HHI',total>0?round(sorted.reduce((s,x)=>s+(x[1]/total)**2,0)*10000):null,'Punkte')],rows:sorted.map(([Produkt,Umsatz])=>({Produkt,'Umsatz €':round(Umsatz),'Umsatzanteil %':ratio(Umsatz,total,100)})),notes:['HHI = Summe quadrierter Produkt-Umsatzanteile × 10.000. Ein Produkt ergibt 10.000 Punkte.','Bei Gesamtumsatz 0 sind Anteile und HHI unbekannt. Der Index beschreibt deinen Produktbestand, keine gesamten Märkte oder Kundenkonzentration.']};}};
T.FeeDetective={name:'Gebührenspur',description:'Berechnet die gewichtete Gebührenquote deiner Aufträge.',labels,example:{orders:[{product:'Produkt A',revenue:100,fees:10},{product:'Produkt B',revenue:900,fees:0}]},run(input){const a=orders(input,['revenue','fees']),r=a.reduce((s,x)=>s+x.revenue,0),f=a.reduce((s,x)=>s+x.fees,0);return{metrics:[m('Gebühren gesamt',round(f),'EUR'),m('Gewichtete Gebührenquote',ratio(f,r,100),'%'),m('Aufträge mit Gebühren',a.filter(x=>x.fees>0).length)],rows:a.map((x,i)=>({Auftrag:i+1,Produkt:x.product,'Umsatz €':x.revenue,'Gebühren €':x.fees,'Gebührenquote %':ratio(x.fees,x.revenue,100)})),notes:['Gewichtete Quote = Gebühren gesamt / Umsatz gesamt × 100. Einzelquoten werden nicht gemittelt.','Bei Umsatz 0 ist die Quote nicht berechenbar. Anbieterpreise werden nicht abgerufen.']};}};
T.ReturnPatternMap={name:'Rückflusskarte',description:'Zeigt den erfassten Erstattungsanteil und die höchsten Erstattungsbeträge.',labels,example:{orders:[{product:'Produkt A',revenue:100,refund:20},{product:'Produkt B',revenue:900,refund:0}]},run(input){const a=orders(input,['revenue','refund']),r=a.reduce((s,x)=>s+x.revenue,0),f=a.reduce((s,x)=>s+x.refund,0),returned=a.map((x,i)=>({...x,order:i+1})).filter(x=>x.refund>0).sort((a,b)=>b.refund-a.refund);return{metrics:[m('Erstattungen gesamt',round(f),'EUR'),m('Erstattungsanteil am Umsatz',ratio(f,r,100),'%'),m('Aufträge mit Erstattung',returned.length)],rows:returned.map(x=>({Auftrag:x.order,Produkt:x.product,'Umsatz €':x.revenue,'Erstattung €':x.refund,'Erstattungsanteil %':ratio(x.refund,x.revenue,100)})),notes:['Quote = Erstattungen / ursprünglicher Auftragsumsatz × 100. Bei Umsatz 0 nicht berechenbar.','Ohne Erstattungsgründe lassen sich Ursachen nicht ableiten. Es werden keine Rückzahlungen ausgeführt.',...(a.some(x=>x.refund>x.revenue)?['Eine Erstattung übersteigt den Umsatz; Zuordnung prüfen.']:[])]};}};
T.StressMatrix={name:'Stresstableau',description:'Vergleicht neun Umsatz- und Fixkostenszenarien.',labels,example:cash,run(input){const x=flow(input),rows=[];for(const r of [.8,1,1.2])for(const f of [.9,1,1.1]){const change=x.monthly_revenue*r*(1-x.variable_cost_rate)-x.monthly_fixed_cost*f;rows.push({'Umsatzniveau %':round(r*100),'Fixkostenniveau %':round(f*100),'Geldänderung €/Monat':round(change),'Reichweite Monate':change<0?ratio(x.cash,-change):null,Einordnung:change<0?'Geldabfluss':'Kein laufender Geldabfluss im Modell'});}return{metrics:[m('Szenarien',9),m('Niedrigster Modellüberschuss',round(x.monthly_revenue*.8*(1-x.variable_cost_rate)-x.monthly_fixed_cost*1.1),'EUR'),m('Höchster Modellüberschuss',round(x.monthly_revenue*1.2*(1-x.variable_cost_rate)-x.monthly_fixed_cost*.9),'EUR')],rows,notes:['Umsatz 80/100/120 %, Fixkosten 90/100/110 %. Der variable Kostenanteil bleibt gleich.','Was-wäre-wenn-Rechnung, keine Vorhersage. Ohne Abfluss gibt es keine endliche Reichweite.']};}};
})();
