// NEULAND-Rechenmotor (motor-belege), unveraendert aus neuland/Belegprobe.html herausgeloest -
// damit Zentrale (Browser) und GitHub Actions (Node) dieselbe Rechnung benutzen.
(() => {
'use strict';const T=window.NeulandTools||={};const MAX=1e12;
const labels={claims:'Aussagen',text:'Aussage',evidence_url:'Beleglink (optional)',verified:'Von dir geprüft',assets:'Verwendete Inhalte',name:'Name',license:'Lizenz / Nutzungsgrundlage',permission:'Freigabe dokumentiert',expires:'Ablaufdatum (JJJJ-MM-TT, optional)',analysis_date:'Prüftag (JJJJ-MM-TT)'};
const error=s=>{throw Error(s);};function object(x,label='Eingabe'){if(!x||typeof x!=='object'||Array.isArray(x))error(label+': Objekt erwartet.');return x;}
function guard(x,path='Eingabe',depth=0){if(depth>12)error('Zu tief verschachtelt.');if(typeof x==='number'&&(!Number.isFinite(x)||Math.abs(x)>MAX))error(path+': Endliche Zahl bis 1 Billion erforderlich.');if(typeof x==='string'&&(x.length>2048||/[\u0000-\u001f\u007f-\u009f]/.test(x)))error(path+': Text ist zu lang oder enthält Steuerzeichen.');if(Array.isArray(x)){if(x.length>100)error(path+': Höchstens 100 Einträge erlaubt.');x.forEach((v,i)=>guard(v,path+'['+i+']',depth+1));}else if(x&&typeof x==='object'){if(Object.keys(x).length>100)error('Zu viele Felder.');Object.keys(x).forEach(k=>guard(x[k],path+'.'+k,depth+1));}}
function input(x){object(x);guard(x);return x;}function rows(x,key){if(x[key]==null)return[];if(!Array.isArray(x[key]))error(key+': Liste erwartet.');return x[key].map(v=>object(v,key));}
function text(x,label){if(x==null)return'';if(typeof x!=='string')error(label+': Text erwartet.');return x.trim();}function bool(x,label){if(x==null)return false;if(typeof x!=='boolean')error(label+': Ja/Nein erwartet.');return x;}
function urlValid(x){if(!x||/\s/.test(x)||!/^https?:\/\//i.test(x))return false;try{const u=new URL(x);return['http:','https:'].includes(u.protocol)&&!!u.hostname&&!u.username&&!u.password;}catch(e){return false;}}
function day(x,label){if(typeof x!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x))error(label+': Gültiges Datum JJJJ-MM-TT erforderlich.');const[y,m,d]=x.split('-').map(Number),v=new Date(0);v.setUTCFullYear(y,m-1,d);v.setUTCHours(0,0,0,0);if(y<1||v.getUTCFullYear()!==y||v.getUTCMonth()!==m-1||v.getUTCDate()!==d)error(label+': Gültiges Kalenderdatum erforderlich.');return v.getTime()/86400000;}
const pct=(a,b)=>b?Math.round(a/b*10000)/100:null;const metric=(label,value,unit='')=>({label,value,unit});
function claims(x){const a=rows(x,'claims').map((r,i)=>{const statement=text(r.text,'Aussage'),evidence=text(r.evidence_url,'Beleglink'),verified=bool(r.verified,'Prüfmarkierung'),quality=statement?[]:['Aussage fehlt.'],issues=[...quality];if(!evidence)issues.push('Beleglink fehlt.');else if(!urlValid(evidence))issues.push('Gültige HTTP-/HTTPS-Adresse ohne Zugangsdaten erforderlich.');if(!verified)issues.push('Menschliche Prüfung ausstehend.');return{text:statement,evidence_url:evidence,verified,quality,issues,ready:!issues.length,index:i+1};});return{list:a,ready:a.filter(x=>x.ready).length};}
function assets(x){const today=day(x.analysis_date,'Prüftag'),a=rows(x,'assets').map((r,i)=>{const name=text(r.name,'Name')||'Asset '+(i+1),license=text(r.license,'Lizenz'),permission=bool(r.permission,'Freigabe'),expires=text(r.expires,'Ablaufdatum'),remaining=expires?day(expires,'Ablaufdatum')-today:null,issues=[];if(!license||['unknown','unbekannt','tbd','?'].includes(license.toLowerCase()))issues.push('Nutzungsgrundlage fehlt.');if(!permission)issues.push('Freigabe nicht dokumentiert.');let status;if(remaining!==null&&remaining<0){issues.push('Freigabe abgelaufen.');status='Abgelaufen';}else if(remaining!==null&&remaining<=30){status=issues.length?'Prüfung offen':'Läuft bald ab';issues.push('Läuft in '+remaining+' Tagen ab; Verlängerung prüfen.');}else status=issues.length?'Prüfung offen':'Dokumentation vollständig';return{name,license,permission,expires,remaining,issues,status,ready:!issues.length};});return{list:a,ready:a.filter(x=>x.ready).length};}
const claimExample={claims:[{text:'Das Paket enthält 30 Checklisten.',evidence_url:'https://example.com/umfang',verified:true},{text:'Alle Kunden verdoppeln ihren Umsatz.',evidence_url:'',verified:false}]};
const assetExample={analysis_date:'2026-10-02',assets:[{name:'Teamfoto',license:'Freigabe für eigene Website',permission:true,expires:'2026-12-31'},{name:'Kampagnenmusik',license:'Befristete Lizenz',permission:true,expires:'2026-10-20'},{name:'Stockbild',license:'',permission:false,expires:''}]};
T.PromiseCheck={name:'Belegprobe',description:'Findet fehlende Beleglinks und offene eigene Prüfmarkierungen.',labels,example:claimExample,run(raw){const r=claims(input(raw));return{metrics:[metric('Aussagen',r.list.length),metric('Prüfung offen',r.list.length-r.ready),metric('Prüfliste erfüllt',r.ready)],rows:r.list.map(x=>({Aussage:x.text,Beleglink:x.evidence_url||'Fehlt','Von dir geprüft':x.verified?'Ja':'Nein',Status:x.ready?'Prüfliste erfüllt':'Prüfung offen',Hinweise:x.issues.join(' ')||'Keine offenen Prüfpunkte.'})),notes:['Beleglinks werden nicht abgerufen. Die Markierung dokumentiert deine eigene Prüfung; Inhalt und Rechtswirksamkeit werden nicht bestätigt.']};}};
T.RightsLedger={name:'Rechtebuch',description:'Findet offene Nutzungsgrundlagen, fehlende Freigaben und erfasste Ablauffristen.',labels,example:assetExample,run(raw){const r=assets(input(raw));return{metrics:[metric('Inhalte',r.list.length),metric('Prüfung offen',r.list.length-r.ready),metric('Dokumentation vollständig',r.ready)],rows:r.list.map(x=>({Inhalt:x.name,Lizenz:x.license||'Fehlt',Freigabe:x.permission?'Erfasst':'Fehlt',Ablauf:x.expires||'Keine Frist erfasst',Resttage:x.remaining,Status:x.status,Hinweise:x.issues.join(' ')||'Keine offenen Prüfpunkte.'})),notes:['Dokumentationsprüfung: Bedingungen, Einsatzgebiet und Belege müssen menschlich geprüft werden. Keine Frist bedeutet keine unbefristete Berechtigung.']};}};
T.EvidenceDebt={name:'Belegschulden',description:'Zeigt Quellenabdeckung und Prüfmarkierungen ohne Quellenverweis.',labels,example:claimExample,run(raw){const r=claims(input(raw)),s=r.list.filter(x=>!!x.evidence_url),u=r.list.filter(x=>x.verified&&!x.evidence_url);return{metrics:[metric('Aussagen mit Quellenverweis',s.length),metric('Quellenabdeckung',pct(s.length,r.list.length),'%'),metric('Als geprüft markiert ohne Quelle',u.length)],rows:r.list.map(x=>({Aussage:x.text,Quellenverweis:x.evidence_url||'Fehlt','Prüfmarkierung ohne Quelle':x.verified&&!x.evidence_url?'Ja':'Nein',Linkformat:!x.evidence_url?'Fehlt':urlValid(x.evidence_url)?'HTTP/HTTPS ohne Zugangsdaten':'Ungültig — prüfen'})),notes:['Abdeckung zählt jeden nichtleeren Verweis. Format, Inhalt und Richtigkeit werden getrennt geprüft; kein Quellenabruf.']};}};
T.RenewalCalendar={name:'Rechtekalender',description:'Zeigt vergangene Ablauffristen und Fälligkeiten innerhalb von 30 Tagen.',labels,example:assetExample,run(raw){const r=assets(input(raw)),expired=r.list.filter(x=>x.remaining!==null&&x.remaining<0),soon=r.list.filter(x=>x.remaining!==null&&x.remaining>=0&&x.remaining<=30);return{metrics:[metric('Abgelaufen',expired.length),metric('Fällig in 30 Tagen',soon.length),metric('Prüftag',raw.analysis_date)],rows:[...expired,...soon].map(x=>({Inhalt:x.name,Ablaufdatum:x.expires,Resttage:x.remaining,Status:x.remaining<0?'Abgelaufen':'Fällig innerhalb 30 Tagen'})),notes:['Heute und der 30. Folgetag zählen zum Fenster. Keine Lizenzverifikation; fehlende Fristen bedeuten keine unbefristete Berechtigung.']};}};
function qualityNumber(row,key,w,o={}){let v=row[key];if(v===undefined){if(o.default!==undefined)v=o.default;else{w.push(key+': Wert fehlt; vorläufig 0.');v=0;}}if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>MAX)error(key+': Endliche Zahl von 0 bis 1 Billion erforderlich.');if(o.max!==undefined&&v>o.max){w.push(key+': Obergrenze überschritten.');v=o.max;}if(o.positive&&v<=0)w.push(key+': Muss größer als 0 sein.');else if(o.positive&&v<1e-9){v=1e-9;w.push(key+': Untergrenze unterschritten.');}if(o.integer&&!Number.isInteger(v)){w.push(key+': Ganze Zahl erforderlich; vorläufig abgerundet.');v=Math.floor(v);}return v;}
function launch(raw){input(raw);day(raw.analysis_date,'Prüftag');const sections=[];function add(key,label,records,evidence=false){const count=records.length,ready=records.filter(x=>x.ready).length;sections.push({key,label,count,ready,evidence,score:count?ready/count*100:0,warnings:records.flatMap(x=>x.warnings||[])});}
add('profit','Deckungsbeitrag',rows(raw,'orders').map(r=>{const w=[],revenue=qualityNumber(r,'revenue',w);qualityNumber(r,'cost',w);const refund=qualityNumber(r,'refund',w,{default:0});qualityNumber(r,'fees',w,{default:0});qualityNumber(r,'quantity',w,{default:1,positive:true,integer:true});if(!text(r.product,'Produkt')||text(r.product,'Produkt')==='Unbenannt')w.push('Produktname fehlt.');if(refund>revenue)w.push('Erstattung übersteigt Umsatz; Zuordnung prüfen.');return{ready:!w.length,warnings:w};}));
const flow=raw.cashflow==null?{}:object(raw.cashflow),fw=[];if(Object.keys(flow).length){const w=[];['cash','monthly_fixed_cost','monthly_revenue'].forEach(k=>qualityNumber(flow,k,w));qualityNumber(flow,'variable_cost_rate',w,{max:1});fw.push({ready:!w.length,warnings:w});}add('runway','Liquidität',fw);
const cap=raw.capacity==null?{}:object(raw.capacity),cw=[];if(Object.keys(cap).length){const w=[];qualityNumber(cap,'hours_available',w);qualityNumber(cap,'hours_per_order',w,{positive:true});qualityNumber(cap,'orders_expected',w,{integer:true});cw.push({ready:!w.length,warnings:w});}add('capacity','Kapazität',cw);
add('experiments','Experimente',rows(raw,'experiments').map(r=>{const w=[];let low=false;['control','variant'].forEach(group=>{const n=qualityNumber(r,group+'_visitors',w,{integer:true});let c=qualityNumber(r,group+'_conversions',w,{integer:true});if(c>n){w.push(group+': Abschlüsse übersteigen Besucher.');c=n;}if(n<100||c<20)low=true;});return{ready:!w.length&&!low,warnings:w};}),true);
add('priorities','Prioritäten',rows(raw,'initiatives').map(r=>{const w=[];qualityNumber(r,'impact',w);qualityNumber(r,'confidence',w,{max:1});qualityNumber(r,'effort',w,{positive:true});return{ready:!w.length,warnings:w};}));const cl=claims(raw),as=assets(raw);add('promises','Aussagen',cl.list.map(x=>({ready:x.ready,warnings:x.quality})),true);add('rights','Nutzungsrechte',as.list.map(x=>({ready:x.ready,warnings:[]})),true);const evidence=sections.filter(x=>x.evidence);return{sections,complete:sections.filter(x=>x.count).length,allReady:sections.every(x=>x.count&&x.ready===x.count&&!x.warnings.length),evidenceCount:evidence.reduce((s,x)=>s+x.count,0),evidenceReady:evidence.reduce((s,x)=>s+x.ready,0),quality:Math.round(sections.reduce((s,x)=>s+x.score,0)/7*100)/100};}
T.LaunchCompass={name:'Startkompass',description:'Prüft Vollständigkeit und Eingabequalität in sieben Geschäftsbereichen.',labels,example:{analysis_date:'2026-10-02',orders:[{product:'Workshop',revenue:490,cost:200,refund:0,fees:18,quantity:1}],cashflow:{cash:12000,monthly_fixed_cost:4800,monthly_revenue:5200,variable_cost_rate:.35},capacity:{hours_available:120,hours_per_order:2,orders_expected:45},experiments:[{name:'Einstiegsseite',control_visitors:1200,control_conversions:48,variant_visitors:1200,variant_conversions:78}],initiatives:[{name:'Onboarding verbessern',impact:8,confidence:.85,effort:2}],claims:[{text:'Der Workshop dauert drei Stunden.',evidence_url:'https://example.com/workshop',verified:true}],assets:[{name:'Eigenes Symbol',license:'Eigene Erstellung',permission:true,expires:''}]},run(raw){const r=launch(raw);return{metrics:[metric('Bereiche mit Daten',r.complete,'/ 7'),metric('Vollständigkeit',pct(r.complete,7),'%'),metric('Mittlere Bereichsqualität',r.quality,'%'),metric('Beleg- und Experimentprüfpunkte erfüllt',pct(r.evidenceReady,r.evidenceCount),'%')],rows:r.sections.map(x=>({Bereich:x.label,Datensätze:x.count,'Erfüllte Prüfpunkte':x.ready,'Bereichsqualität (%)':pct(x.ready,x.count)??0,Status:!x.count?'Daten fehlen':x.ready===x.count&&!x.warnings.length?'Prüfliste erfüllt':'Offene Daten- oder Belegprüfung',Hinweise:x.warnings.join(' ')||(!x.count?'Daten ergänzen.':x.ready<x.count?'Eigene Prüfung oder Experimentdaten ergänzen.':'Keine offenen Prüfpunkte.')})),notes:[r.allReady?'Prüfliste vollständig.':'Offene Punkte bearbeiten.','Vollständigkeit = vorhandene Bereiche / 7. Qualität = Mittel von sieben Prüfanteilen; fehlende Bereiche zählen als 0 %.','Experimente benötigen mindestens 100 Besucher und 20 Abschlüsse je Gruppe. Verlustaufträge und Kapazitätslücken sind keine Eingabefehler.','Keine Bestätigung von Nachfrage, Rechtskonformität oder Produktionsreife. Keine Quellen oder Bedingungen werden abgerufen.']};}};
})();
