// NEULAND-Rechenmotor (motor-tests), unveraendert aus neuland/Versuchsfeld.html herausgeloest -
// damit Zentrale (Browser) und GitHub Actions (Node) dieselbe Rechnung benutzen.
(() => {
'use strict';const T=window.NeulandTools||={};const z=1.959963984540054,MAX=1e12;
const labels={experiments:'Versuche',name:'Bezeichnung',control_visitors:'Besucher Kontrolle',control_conversions:'Abschlüsse Kontrolle',variant_visitors:'Besucher Variante',variant_conversions:'Abschlüsse Variante',priorities:'Vorhaben',impact:'Wirkung (Punkte)',confidence:'Vertrauen (0–1)',effort:'Aufwand (gleiche Einheit)',decisions:'Entscheidungen',title:'Titel',hypothesis:'Hypothese',action:'Maßnahme',expected_result:'Erwartetes Ergebnis',outcome:'Beobachtetes Ergebnis',status:'Status'};
function num(x,label,{positive=false,integer=false,upper=MAX}={}){if(typeof x!=='number'||!Number.isFinite(x)||x<0||x>upper||(positive&&x<1e-9)||(integer&&!Number.isInteger(x)))throw Error(label+': gültige '+(integer?'ganze ':'')+'Zahl '+(positive?'ab 0,000000001':'ab 0')+' bis '+upper+' erforderlich.');return x;}
function text(x,label,{empty=true,limit=2000}={}){if(typeof x!=='string'||x.length>limit||(!empty&&!x.trim()))throw Error(label+': '+(empty?'':'nicht leerer ')+'Text mit höchstens '+limit+' Zeichen erforderlich.');return x.trim();}
function list(input,key){if(!input||typeof input!=='object'||!Array.isArray(input[key])||input[key].length>100)throw Error(key+': Liste mit höchstens 100 Einträgen erforderlich.');input[key].forEach(x=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Jeder Eintrag muss ein Objekt sein.');});return input[key];}
const round=(x,p=4)=>x===null?null:Number(x.toFixed(p));
function wilson(c,n){if(!n)return[null,null];const p=c/n,z2=z*z,d=1+z2/n,center=(p+z2/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z2/(4*n*n))/d;return[Math.max(0,center-half),Math.min(1,center+half)];}
const interval=x=>x[0]===null?'Unbekannt (keine Besucher)':`${(x[0]*100).toFixed(2)}–${(x[1]*100).toFixed(2)} %`;
function arm(row,key){const n=num(row[key+'_visitors'],labels[key+'_visitors'],{integer:true}),c=num(row[key+'_conversions'],labels[key+'_conversions'],{integer:true});if(c>n)throw Error('Abschlüsse dürfen Besucher nicht übersteigen.');return{n,c,rate:n?c/n:null,ci:wilson(c,n)};}
T.ExperimentLab={name:'Versuchsfeld',description:'Vergleicht beobachtete Abschlussquoten mit 95-%-Wilson-Intervallen je Gruppe.',labels,example:{experiments:[{name:'Angebotsseite',control_visitors:1000,control_conversions:100,variant_visitors:1000,variant_conversions:150}]},run(input){let lowCount=0;const notes=['Beobachtete Veränderung, keine bewiesene Ursache. Zufällige und unabhängige Zuteilung bleibt Voraussetzung.','Getrennte Wilson-Intervalle sind ein konservatives Signal, kein direkter Signifikanztest und keine Korrektur für wiederholtes Nachschauen.'];const rows=list(input,'experiments').map(row=>{const name=text(row.name,'Bezeichnung',{empty:false,limit:200}),a=arm(row,'control'),b=arm(row,'variant'),available=a.n>0&&b.n>0,low=[a,b].some(x=>x.n<100||x.c<20),overlap=available?Math.max(a.ci[0],b.ci[0])<=Math.min(a.ci[1],b.ci[1]):null,change=available?(b.rate-a.rate)*100:null,lift=available&&a.rate>0?(b.rate/a.rate-1)*100:null;if(low){lowCount++;notes.push(name+': Weniger als 100 Besucher oder 20 Abschlüsse je Gruppe; mehr Daten nötig.');}return{Versuch:name,'Kontrolle (%)':round(a.rate===null?null:a.rate*100),'95-%-Intervall Kontrolle':interval(a.ci),'Variante (%)':round(b.rate===null?null:b.rate*100),'95-%-Intervall Variante':interval(b.ci),'Veränderung (Prozentpunkte)':round(change),'Relativer Lift (%)':round(lift),Einschätzung:low?'Mehr Daten nötig':overlap?'Kein belastbarer Unterschied':change>0?'Variante aussichtsreich':'Kontrolle aussichtsreich'};});return{metrics:[{label:'Versuche',value:rows.length},{label:'Versuche mit wenig Daten',value:lowCount}],rows,notes};}};
T.ValueMap={name:'Vorhabenwaage',description:'Ordnet Vorhaben nach eingeschätzter Wirkung × Vertrauen ÷ Aufwand.',labels,example:{priorities:[{name:'Onboarding vereinfachen',impact:8,confidence:.8,effort:4},{name:'Handbuch ergänzen',impact:5,confidence:.9,effort:2}]},run(input){const a=list(input,'priorities').map(row=>{const name=text(row.name,'Bezeichnung',{empty:false,limit:200}),impact=num(row.impact,'Wirkung'),confidence=num(row.confidence,'Vertrauen',{upper:1}),effort=num(row.effort,'Aufwand',{positive:true}),score=impact*confidence/effort;if(!Number.isFinite(score))throw Error('Bewertung überschreitet den Rechenbereich.');return{name,impact,confidence,effort,score};}).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));return{metrics:[{label:'Vorhaben',value:a.length},{label:'Höchste Bewertung',value:a.length?round(a[0].score):null}],rows:a.map((r,i)=>({Rang:i+1,Vorhaben:r.name,Wirkung:r.impact,Vertrauen:r.confidence,Aufwand:r.effort,Bewertung:round(r.score)})),notes:['Formel: Wirkung × Vertrauen ÷ Aufwand. Wirkung und Aufwand müssen vergleichbar bewertet werden.','Subjektive Einschätzungen, keine Umsatzprognose. Vertrauen 0–1, Aufwand mindestens 0,000000001.']};}};
T.ExperimentSamplePlanner={name:'Testkompass',description:'Plant die Gruppengröße eines Tests für angenommene 20 % relative Verbesserung.',labels,example:{experiments:[{name:'Angebotsseite',control_visitors:1000,control_conversions:100}]},run(input){const samples=[];const rows=list(input,'experiments').map(row=>{const name=text(row.name,'Bezeichnung',{empty:false,limit:200}),a=arm(row,'control'),p=a.rate,target=p===null?null:p*1.2;if(!(p>0&&p<target&&target<1))return{Versuch:name,'Basisrate (%)':p===null?null:round(p*100),'Zielrate (%)':null,'Besucher je Gruppe':null,Gesamtbesucher:null,Hinweis:'Basisrate zwischen 0 % und 83,33 % erforderlich.'};const mean=(p+target)/2,n=Math.ceil(((1.959964*Math.sqrt(2*mean*(1-mean))+.841621*Math.sqrt(p*(1-p)+target*(1-target)))/(target-p))**2);if(!Number.isSafeInteger(n)||!Number.isSafeInteger(n*2))throw Error('Besucherplanung übersteigt den Rechenbereich.');samples.push(n);return{Versuch:name,'Basisrate (%)':round(p*100),'Zielrate (%)':round(target*100),'Besucher je Gruppe':n,Gesamtbesucher:n*2,Hinweis:'Ungefähre Planung für zwei gleich große Gruppen.'};});return{metrics:[{label:'Planbare Versuche',value:samples.length},{label:'Größtes Ziel je Gruppe',value:samples.length?Math.max(...samples):null,unit:'Besucher'}],rows,notes:['Normalapproximation: zwei unabhängige Anteile, zweiseitiges α = 5 %, Power = 80 %, gleiche Gruppen, angenommener relativer Lift 20 %.','Die beobachtete Basisrate ist unsicher. Planung ist eine Größenordnung, keine Erfolgsgarantie; keine Korrektur für mehrere Tests oder wiederholtes Nachschauen.']};}};
T.DecisionJournal={name:'Entscheidungsbuch',journal:true,description:'Hält Hypothesen, Maßnahmen, Erwartungen und beobachtete Ergebnisse fest.',labels,example:{decisions:[{title:'Onboarding kürzen',hypothesis:'Weniger Schritte erhöhen den Abschlussanteil.',action:'Zwei Schritte zusammenlegen.',expected_result:'Mehr Abschlüsse bei gleicher Besucherzahl.',outcome:'',status:'open'}]},run(input){const statuses={open:'Offen',learned:'Ausgewertet',discarded:'Verworfen'},count={open:0,learned:0,discarded:0};const rows=list(input,'decisions').map(row=>{const title=text(row.title,'Titel',{empty:false,limit:160});if(!Object.hasOwn(statuses,row.status))throw Error('Status muss open, learned oder discarded sein.');count[row.status]++;return{Titel:title,Hypothese:text(row.hypothesis,'Hypothese'),Maßnahme:text(row.action,'Maßnahme'),'Erwartetes Ergebnis':text(row.expected_result,'Erwartetes Ergebnis'),'Beobachtetes Ergebnis':text(row.outcome,'Beobachtetes Ergebnis'),Status:statuses[row.status]};});return{metrics:[{label:'Entscheidungen',value:rows.length},{label:'Offen',value:count.open},{label:'Ausgewertet',value:count.learned},{label:'Verworfen',value:count.discarded}],rows,notes:['Dieses eigenständige Journal ist vom SQLite-Journal der Hauptanwendung getrennt.','Änderungen speichern und regelmäßig als JSON exportieren. Browserdaten können gelöscht werden.','Statuswerte: open = offen, learned = ausgewertet, discarded = verworfen. Ergebnisse werden nicht automatisch bewertet.']};}};
})();
