// Geprüfte Fakten für den Fakten-Kanal (#100): jeder Eintrag ist von Hand kontrolliert und unstrittig.
// Die kleine lokale KI erfand oder verdrehte Fakten (falsche Quiz-Antworten) - deshalb kommen Frage, Antwort und
// Erklärung hier aus der Liste; die KI wird nur noch als Notnagel gebraucht, wenn die Liste leer ist.
// Eintrag quiz:   { typ, kat, titel, hook, frage, optionen[3], richtig (0-2), erklaerung[], caption, bilder[3] }
// Eintrag mythos: { typ, kat, titel, hook, aussage, wahr, erklaerung[], caption, bilder[3] }
const q = (kat, titel, frage, optionen, richtig, erklaerung, tags, bilder) => ({ typ: 'quiz', kat, titel, hook: 'Schaffst du diese Frage?', frage, optionen, richtig, erklaerung, caption: `${frage} Schreib deine Antwort in die Kommentare! ${tags}`, bilder });
const m = (kat, titel, aussage, wahr, erklaerung, tags, bilder) => ({ typ: 'mythos', kat, titel, hook: 'Mythos oder Wahrheit?', aussage, wahr, erklaerung, caption: `${aussage} Wahr oder Mythos? Schreib es in die Kommentare! ${tags}`, bilder });
const ph = (t) => [`${t}, cinematic, photorealistic, dramatic light, no text, no people`, `${t}, close-up detail, cinematic, no text, no people`, `${t}, wide epic shot, cinematic, no text, no people`];

const QUIZ = [
  q('Weltall', 'Der heißeste Planet', 'Welcher Planet ist der heißeste im Sonnensystem?', ['Merkur', 'Venus', 'Mars'], 1, ['Die Venus hat eine dichte Kohlendioxid-Atmosphäre, die die Wärme einsperrt.', 'Dort herrschen rund 465 Grad Celsius.'], '#Weltall #Venus #Planeten #Quiz #Wissen', ph('planet Venus with thick glowing clouds in space')),
  q('Körper', 'Das größte Organ', 'Welches ist das größte Organ des Menschen?', ['Die Leber', 'Die Haut', 'Die Lunge'], 1, ['Die Haut bedeckt den ganzen Körper und ist unser größtes Organ.'], '#Körper #Haut #Organe #Quiz #Wissen', ph('macro texture of skin cells, abstract biology')),
  q('Weltall', 'Wie schnell ist das Sonnenlicht', 'Wie lange braucht das Licht der Sonne bis zur Erde?', ['Etwa 8 Sekunden', 'Etwa 8 Minuten', 'Etwa 8 Stunden'], 1, ['Das Sonnenlicht ist etwa acht Minuten unterwegs.', 'Wir sehen die Sonne also immer so, wie sie vor acht Minuten war.'], '#Weltall #Sonne #Licht #Quiz #Wissen', ph('the sun with bright rays seen from space')),
  q('Körper', 'Knochen beim Erwachsenen', 'Wie viele Knochen hat ein erwachsener Mensch?', ['206', '150', '300'], 0, ['Ein Erwachsener hat 206 Knochen.', 'Babys haben mehr, viele davon wachsen später zusammen.'], '#Körper #Knochen #Skelett #Quiz #Wissen', ph('human skeleton model in a dark museum')),
  q('Natur', 'Das häufigste Element', 'Welches ist das häufigste Element im Universum?', ['Sauerstoff', 'Helium', 'Wasserstoff'], 2, ['Wasserstoff macht den größten Teil der gewöhnlichen Materie im Universum aus.', 'Auch die Sterne bestehen vor allem daraus.'], '#Universum #Wasserstoff #Chemie #Quiz #Wissen', ph('glowing hydrogen nebula in deep space')),
  q('Körper', 'Das Herz', 'Aus wie vielen Räumen besteht das menschliche Herz?', ['Zwei', 'Vier', 'Sechs'], 1, ['Das Herz hat zwei Vorhöfe und zwei Kammern, also vier Räume.'], '#Herz #Körper #Anatomie #Quiz #Wissen', ph('anatomical human heart model, dramatic light')),
  q('Natur', 'Das flüssige Metall', 'Welches Metall ist bei Zimmertemperatur flüssig?', ['Blei', 'Quecksilber', 'Zinn'], 1, ['Quecksilber ist das bekannteste Metall, das bei Zimmertemperatur flüssig ist.'], '#Chemie #Quecksilber #Metall #Quiz #Wissen', ph('shiny liquid mercury droplets on dark surface')),
  q('Tiere', 'Spinnenbeine', 'Wie viele Beine hat eine Spinne?', ['Sechs', 'Acht', 'Zehn'], 1, ['Spinnen haben acht Beine.', 'Insekten haben dagegen sechs.'], '#Tiere #Spinne #Natur #Quiz #Wissen', ph('spider on a dew covered web at sunrise')),
  q('Körper', 'Die Zähne', 'Wie viele Zähne hat ein erwachsenes Gebiss mit Weisheitszähnen?', ['28', '32', '36'], 1, ['Ein vollständiges Erwachsenengebiss hat 32 Zähne.', 'Ohne Weisheitszähne sind es 28.'], '#Zähne #Körper #Gesundheit #Quiz #Wissen', ph('abstract white teeth shapes macro photography')),
  q('Natur', 'Der größte Ozean', 'Welcher ist der größte Ozean der Erde?', ['Der Atlantik', 'Der Indische Ozean', 'Der Pazifik'], 2, ['Der Pazifik ist der größte und tiefste Ozean der Erde.'], '#Ozean #Pazifik #Erde #Quiz #Wissen', ph('vast blue pacific ocean waves from above')),
  q('Natur', 'Pflanzen und Gas', 'Welches Gas nehmen Pflanzen für die Photosynthese auf?', ['Kohlendioxid', 'Sauerstoff', 'Stickstoff'], 0, ['Pflanzen nehmen Kohlendioxid auf und geben dabei Sauerstoff ab.'], '#Pflanzen #Photosynthese #Natur #Quiz #Wissen', ph('green leaves with sunlight rays in a forest')),
  q('Natur', 'Wasser auf der Erde', 'Wie viel der Erdoberfläche ist von Wasser bedeckt?', ['Etwa 30 Prozent', 'Etwa 50 Prozent', 'Etwa 70 Prozent'], 2, ['Rund 70 Prozent der Erdoberfläche sind von Wasser bedeckt.', 'Deshalb nennt man die Erde auch den blauen Planeten.'], '#Erde #Wasser #Planet #Quiz #Wissen', ph('planet earth seen from space, blue oceans')),
  q('Körper', 'Der kleinste Knochen', 'Wo sitzt der kleinste Knochen des menschlichen Körpers?', ['Im Ohr', 'Im Finger', 'Im Fuß'], 0, ['Der Steigbügel im Mittelohr ist der kleinste Knochen des Menschen.', 'Er ist nur wenige Millimeter groß.'], '#Körper #Ohr #Knochen #Quiz #Wissen', ph('abstract inner ear structure, macro, dark background')),
  q('Weltall', 'Die Erdtrabanten', 'Wie viele natürliche Monde hat die Erde?', ['Einen', 'Zwei', 'Drei'], 0, ['Die Erde hat genau einen natürlichen Mond.'], '#Mond #Weltall #Erde #Quiz #Wissen', ph('full moon over a dark mountain landscape')),
  q('Geld', 'Das Symbol Au', 'Welches Edelmetall hat das chemische Symbol Au?', ['Silber', 'Gold', 'Platin'], 1, ['Au kommt vom lateinischen Wort aurum und steht für Gold.'], '#Gold #Chemie #Geld #Quiz #Wissen', ph('gold bars glittering in dramatic light')),
];

const MYTHOS = [
  m('Natur', 'Blitze schlagen doppelt ein', 'Blitze schlagen nie zweimal an derselben Stelle ein.', false, ['Das stimmt nicht.', 'Hohe Gebäude und Türme werden sogar mehrmals im Jahr vom Blitz getroffen.'], '#Blitz #Wetter #Natur #Mythos #Wissen', ph('lightning bolt striking over a city skyline at night')),
  m('Essen', 'Honig verdirbt kaum', 'Honig verdirbt praktisch nie.', true, ['Honig enthält sehr wenig Wasser und ist leicht sauer.', 'Bakterien kommen darin kaum zurecht, deshalb hält er extrem lange.'], '#Honig #Essen #Natur #Wahrheit #Wissen', ph('golden honey dripping from a wooden dipper')),
  m('Körper', 'Zehn Prozent vom Gehirn', 'Wir nutzen nur zehn Prozent unseres Gehirns.', false, ['Das ist ein Mythos.', 'Fast alle Bereiche des Gehirns sind aktiv, nur nicht alle gleichzeitig.'], '#Gehirn #Körper #Mythos #Wissen #Psychologie', ph('glowing neural network abstract brain visualization')),
  m('Tiere', 'Das Goldfisch-Gedächtnis', 'Goldfische haben nur ein Gedächtnis von drei Sekunden.', false, ['Das stimmt nicht.', 'Goldfische können sich Wochen bis Monate an Dinge erinnern, zum Beispiel an Futterzeiten.'], '#Goldfisch #Tiere #Mythos #Natur #Wissen', ph('orange goldfish swimming in clear water')),
  m('Natur', 'Die Chinesische Mauer', 'Die Chinesische Mauer ist vom Mond aus mit bloßem Auge zu sehen.', false, ['Das ist ein Mythos.', 'Die Mauer ist zwar sehr lang, aber viel zu schmal, um vom Mond aus erkennbar zu sein.'], '#Mauer #China #Mythos #Weltall #Wissen', ph('ancient great wall winding over green mountains')),
  m('Körper', 'Mehr als fünf Sinne', 'Der Mensch hat mehr als fünf Sinne.', true, ['Neben Sehen, Hören, Riechen, Schmecken und Fühlen gibt es zum Beispiel den Gleichgewichtssinn.', 'Auch Temperatur und Körperlage nehmen wir wahr.'], '#Sinne #Körper #Wahrheit #Wissen #Psychologie', ph('abstract colorful senses concept, eye and ear shapes, no people')),
  m('Natur', 'Bananen und Bäume', 'Bananen wachsen an Bäumen.', false, ['Das stimmt nicht.', 'Bananenpflanzen sind Stauden, keine Bäume. Der Stamm besteht aus fest ineinander liegenden Blättern.'], '#Bananen #Pflanzen #Mythos #Natur #Wissen', ph('banana plant with a large bunch of green bananas')),
  m('Tiere', 'Blinde Fledermäuse', 'Fledermäuse sind blind.', false, ['Das ist ein Mythos.', 'Fledermäuse können sehen und nutzen zusätzlich Ultraschall, um sich im Dunkeln zu orientieren.'], '#Fledermaus #Tiere #Mythos #Natur #Wissen', ph('bat flying at dusk against a purple sky')),
  m('Weltall', 'Die Farbe der Sonne', 'Die Sonne ist in Wahrheit weiß.', true, ['Die Sonne strahlt im ganzen Farbspektrum und wirkt aus dem Weltall weiß.', 'Gelb erscheint sie uns nur durch die Erdatmosphäre.'], '#Sonne #Weltall #Wahrheit #Licht #Wissen', ph('bright white sun with solar flares in space')),
  m('Weltall', 'Venus Tag und Jahr', 'Ein Tag auf der Venus dauert länger als ein Jahr auf der Venus.', true, ['Die Venus dreht sich extrem langsam um sich selbst, für eine Drehung braucht sie etwa 243 Erdtage.', 'Für eine Runde um die Sonne braucht sie nur etwa 225 Erdtage.'], '#Venus #Weltall #Wahrheit #Planeten #Wissen', ph('planet Venus slowly rotating, golden clouds')),
  m('Tiere', 'Strauß und Sand', 'Strauße stecken bei Gefahr den Kopf in den Sand.', false, ['Das ist ein Mythos.', 'Strauße legen den Kopf manchmal an den Boden, um an ihr Nest zu kommen, oder rennen bei Gefahr einfach davon.'], '#Strauß #Tiere #Mythos #Natur #Wissen', ph('ostrich walking in an african savanna at sunset')),
  m('Körper', 'Fingerabdrücke bei Zwillingen', 'Selbst eineiige Zwillinge haben unterschiedliche Fingerabdrücke.', true, ['Fingerabdrücke entstehen schon im Mutterleib und werden auch durch Zufälle geformt.', 'Deshalb sind sie bei jedem Menschen einzigartig.'], '#Fingerabdruck #Zwillinge #Körper #Wahrheit #Wissen', ph('macro of a fingerprint pattern glowing, abstract')),
  m('Weltall', 'Der Mond entfernt sich', 'Der Mond entfernt sich jedes Jahr ein paar Zentimeter von der Erde.', true, ['Der Mond wandert pro Jahr etwa knapp vier Zentimeter weiter weg.', 'Das haben Messungen mit Laserstrahlen gezeigt.'], '#Mond #Weltall #Wahrheit #Erde #Wissen', ph('moon rising behind the earth horizon from space')),
  m('Körper', 'Haare nach dem Tod', 'Haare und Fingernägel wachsen nach dem Tod weiter.', false, ['Das ist ein Mythos.', 'Die Haut zieht sich zurück und trocknet aus, dadurch wirken Haare und Nägel länger.'], '#Körper #Haare #Mythos #Wissen #Anatomie', ph('abstract dark macro texture of hair strands')),
  m('Essen', 'Zucker und Hyperaktivität', 'Zucker macht Kinder hyperaktiv.', false, ['Das haben viele Studien nicht bestätigt.', 'Wahrscheinlich liegt es eher an der Aufregung auf Partys, nicht am Zucker.'], '#Zucker #Essen #Mythos #Wissen #Kinder', ph('colorful candy pile, studio light')),
];

// Abwechselnd Quiz und Mythos - so wiederholt sich das Format nicht.
export const BANK = QUIZ.flatMap((e, i) => (MYTHOS[i] ? [e, MYTHOS[i]] : [e])).map((e, i) => ({ ...e, id: `b${i + 1}` }));

// Naechster noch nicht benutzter Eintrag (verwendet = Liste benutzter ids), sonst null.
export const bankNaechster = (verwendet = []) => BANK.find((e) => !verwendet.includes(e.id)) || null;
