// Geprüfte Fakten für den Fakten-Kanal (#100): jeder Eintrag ist von Hand kontrolliert und unstrittig.
// Die kleine lokale KI erfand oder verdrehte Fakten (falsche Quiz-Antworten) - deshalb kommen Frage, Antwort und
// Erklärung hier aus der Liste; die KI wird nur noch als Notnagel gebraucht, wenn die Liste leer ist.
// Eintrag quiz:   { typ, kat, titel, hook, frage, optionen[3], richtig (0-2), erklaerung[], caption, bilder[3] }
// Eintrag mythos: { typ, kat, titel, hook, aussage, wahr, erklaerung[], caption, bilder[3] }
const q = (kat, titel, frage, optionen, richtig, erklaerung, tags, bilder) => ({ typ: 'quiz', kat, titel, hook: 'Schaffst du diese Frage?', frage, optionen, richtig, erklaerung, caption: `${frage} Schreib deine Antwort in die Kommentare! ${tags}`, bilder });
const m = (kat, titel, aussage, wahr, erklaerung, tags, bilder) => ({ typ: 'mythos', kat, titel, hook: 'Mythos oder Wahrheit?', aussage, wahr, erklaerung, caption: `${aussage} Wahr oder Mythos? Schreib es in die Kommentare! ${tags}`, bilder });
const ph = (t) => [`${t}, cinematic, photorealistic, dramatic light, no text, no people`, `${t}, close-up detail, cinematic, no text, no people`, `${t}, wide epic shot, cinematic, no text, no people`];

const QUIZ = [
  q('Weltall', 'Der heißeste Planet', 'Welcher Planet ist der heißeste im Sonnensystem?', ['Merkur', 'Venus', 'Mars'], 1, ['Die Venus hat eine dichte Kohlendioxid-Atmosphäre, die die Wärme einsperrt.', 'Dort herrschen rund 465 Grad Celsius.'], '#Weltall #Venus #Planeten #Quiz #Wissen', ph('planet Venus with thick glowing clouds in space')),
  q('Körper', 'Das größte Organ', 'Welches ist das größte Organ des Menschen?', ['Die Leber', 'Die Haut', 'Die Lunge'], 1, ['Die Haut bedeckt den ganzen Körper und ist unser größtes Organ.'], '#Körper #Haut #Organe #Quiz #Wissen', ph('macro texture of skin cells, abstract biology')),
  q('Weltall', 'Wie schnell ist das Sonnenlicht', 'Wie lange braucht das Licht der Sonne bis zur Erde?', ['Etwa 8 Sekunden', 'Etwa 8 Minuten', 'Etwa 8 Stunden'], 1, ['Das Sonnenlicht ist etwa acht Minuten unterwegs.', 'Wir sehen die Sonne also immer so, wie sie vor acht Minuten war.'], '#Weltall #Sonne #Licht #Quiz #Wissen', ph('the sun with bright rays seen from space')),
  q('Körper', 'Knochen beim Erwachsenen', 'Wie viele Knochen hat ein erwachsener Mensch?', ['206', '150', '300'], 0, ['Ein Erwachsener hat 206 Knochen.', 'Babys haben mehr, viele davon wachsen später zusammen.'], '#Körper #Knochen #Skelett #Quiz #Wissen', ph('human skeleton model in a dark museum')),
  q('Natur', 'Das häufigste Element', 'Welches ist das häufigste Element im Universum?', ['Sauerstoff', 'Helium', 'Wasserstoff'], 2, ['Wasserstoff macht den größten Teil der gewöhnlichen Materie im Universum aus.', 'Auch die Sterne bestehen vor allem daraus.'], '#Universum #Wasserstoff #Chemie #Quiz #Wissen', ph('glowing hydrogen nebula in deep space')),
  q('Körper', 'Das Herz', 'Aus wie vielen Räumen besteht das menschliche Herz?', ['Zwei', 'Vier', 'Sechs'], 1, ['Das Herz hat zwei Vorhöfe und zwei Kammern, also vier Räume.'], '#Herz #Körper #Anatomie #Quiz #Wissen', ph('anatomical human heart model, dramatic light')),
  q('Natur', 'Das flüssige Metall', 'Welches Metall ist bei Zimmertemperatur flüssig?', ['Blei', 'Quecksilber', 'Zinn'], 1, ['Quecksilber ist das bekannteste Metall, das bei Zimmertemperatur flüssig ist.'], '#Chemie #Quecksilber #Metall #Quiz #Wissen', ph('shiny liquid mercury droplets on dark surface')),
  q('Tiere', 'Spinnenbeine', 'Wie viele Beine hat eine Spinne?', ['Sechs', 'Acht', 'Zehn'], 1, ['Spinnen haben acht Beine.', 'Insekten haben dagegen sechs.'], '#Tiere #Spinne #Natur #Quiz #Wissen', ph('spider on a dew covered web at sunrise')),
  q('Körper', 'Die Zähne', 'Wie viele Zähne hat ein erwachsenes Gebiss mit Weisheitszähnen?', ['28', '32', '36'], 1, ['Ein vollständiges Erwachsenengebiss hat 32 Zähne.', 'Ohne Weisheitszähne sind es 28.'], '#Zähne #Körper #Gesundheit #Quiz #Wissen', ph('abstract white teeth shapes macro photography')),
  q('Natur', 'Der größte Ozean', 'Welcher ist der größte Ozean der Erde?', ['Der Atlantik', 'Der Indische Ozean', 'Der Pazifik'], 2, ['Der Pazifik ist der größte und tiefste Ozean der Erde.'], '#Ozean #Pazifik #Erde #Quiz #Wissen', ph('vast blue pacific ocean waves from above')),
  q('Natur', 'Pflanzen und Gas', 'Welches Gas nehmen Pflanzen für die Photosynthese auf?', ['Kohlendioxid', 'Sauerstoff', 'Stickstoff'], 0, ['Pflanzen nehmen Kohlendioxid auf und geben dabei Sauerstoff ab.'], '#Pflanzen #Photosynthese #Natur #Quiz #Wissen', ph('green leaves with sunlight rays in a forest')),
  q('Natur', 'Wasser auf der Erde', 'Wie viel der Erdoberfläche ist von Wasser bedeckt?', ['Etwa 30 Prozent', 'Etwa 50 Prozent', 'Etwa 70 Prozent'], 2, ['Rund 70 Prozent der Erdoberfläche sind von Wasser bedeckt.', 'Deshalb nennt man die Erde auch den blauen Planeten.'], '#Erde #Wasser #Planet #Quiz #Wissen', ph('planet earth seen from space, blue oceans')),
  q('Körper', 'Der kleinste Knochen', 'Wo sitzt der kleinste Knochen des menschlichen Körpers?', ['Im Ohr', 'Im Finger', 'Im Fuß'], 0, ['Der Steigbügel im Mittelohr ist der kleinste Knochen des Menschen.', 'Er ist nur wenige Millimeter groß.'], '#Körper #Ohr #Knochen #Quiz #Wissen', ph('abstract inner ear structure, macro, dark background')),
  q('Weltall', 'Die Erdtrabanten', 'Wie viele natürliche Monde hat die Erde?', ['Einen', 'Zwei', 'Drei'], 0, ['Die Erde hat genau einen natürlichen Mond.'], '#Mond #Weltall #Erde #Quiz #Wissen', ph('full moon over a dark mountain landscape')),
  q('Geld', 'Das Symbol Au', 'Welches Edelmetall hat das chemische Symbol Au?', ['Silber', 'Gold', 'Platin'], 1, ['Au kommt vom lateinischen Wort aurum und steht für Gold.'], '#Gold #Chemie #Geld #Quiz #Wissen', ph('gold bars glittering in dramatic light')),
  q('Weltall', 'Der Rote Planet', 'Welcher Planet wird Roter Planet genannt?', ['Mars', 'Jupiter', 'Merkur'], 0, ['Der Mars wirkt rot, weil sein Staub viel Eisenoxid enthält.', 'Eisenoxid kennen wir auch als Rost.'], '#Mars #Weltall #Planeten #Quiz #Wissen', ph('red planet Mars surface with dust storms')),
  q('Körper', 'Chromosomen beim Menschen', 'Wie viele Chromosomen hat ein Mensch normalerweise in jeder Körperzelle?', ['23', '46', '64'], 1, ['Ein Mensch hat 46 Chromosomen, also 23 Paare.', 'Die eine Hälfte kommt von der Mutter, die andere vom Vater.'], '#Körper #Gene #Biologie #Quiz #Wissen', ph('abstract glowing dna helix on dark background')),
  q('Natur', 'Kochendes Wasser', 'Bei wie viel Grad Celsius kocht Wasser auf Meereshöhe?', ['90 Grad', '100 Grad', '110 Grad'], 1, ['Auf Meereshöhe kocht Wasser bei 100 Grad Celsius.', 'In den Bergen kocht es schon bei weniger, weil dort der Luftdruck niedriger ist.'], '#Wasser #Physik #Natur #Quiz #Wissen', ph('boiling water bubbles in a steel pot, steam')),
  q('Weltall', 'Unsere Galaxie', 'Wie heißt die Galaxie, in der unser Sonnensystem liegt?', ['Andromeda', 'Milchstraße', 'Sombrero'], 1, ['Unser Sonnensystem liegt in der Milchstraße.', 'Sie besteht aus mehreren hundert Milliarden Sternen.'], '#Milchstraße #Weltall #Galaxie #Quiz #Wissen', ph('milky way galaxy arching over a dark landscape')),
  q('Körper', 'Das Filterorgan', 'Welches Organ filtert das Blut und bildet den Urin?', ['Die Leber', 'Die Niere', 'Die Milz'], 1, ['Die Nieren filtern das Blut und scheiden Abfallstoffe mit dem Urin aus.', 'Jeder Mensch hat normalerweise zwei davon.'], '#Körper #Niere #Organe #Quiz #Wissen', ph('abstract kidney shaped anatomical model, dark background')),
  q('Natur', 'Gas in der Luft', 'Welches Gas macht den größten Teil der Luft aus?', ['Sauerstoff', 'Kohlendioxid', 'Stickstoff'], 2, ['Fast 78 Prozent der Luft bestehen aus Stickstoff.', 'Sauerstoff macht nur etwa 21 Prozent aus.'], '#Luft #Atmosphäre #Natur #Quiz #Wissen', ph('earth atmosphere glowing blue line seen from space')),
  q('Tiere', 'Das fliegende Säugetier', 'Welches Säugetier kann richtig fliegen?', ['Flughörnchen', 'Fledermaus', 'Känguru'], 1, ['Fledermäuse sind die einzigen Säugetiere, die aktiv fliegen können.', 'Flughörnchen gleiten nur.'], '#Fledermaus #Tiere #Natur #Quiz #Wissen', ph('bat in flight at night with moonlight')),
  q('Geld', 'Dividende', 'Wie nennt man den Gewinnanteil, den eine Aktiengesellschaft an ihre Aktionäre zahlt?', ['Dividende', 'Kupon', 'Provision'], 0, ['Der ausgezahlte Gewinnanteil heißt Dividende.', 'Nicht jede Aktiengesellschaft zahlt eine.'], '#Geld #Aktien #Dividende #Quiz #Wissen', ph('stock market charts glowing on dark screens, no people')),
  q('Weltall', 'Der Planet am Rand', 'Welcher Planet ist am weitesten von der Sonne entfernt?', ['Uranus', 'Neptun', 'Saturn'], 1, ['Neptun ist der äußerste Planet im Sonnensystem.', 'Pluto zählt seit 2006 als Zwergplanet.'], '#Neptun #Weltall #Planeten #Quiz #Wissen', ph('deep blue planet Neptune with white clouds')),
  q('Körper', 'Vitamin aus Sonnenlicht', 'Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?', ['Vitamin C', 'Vitamin D', 'Vitamin K'], 1, ['Unter Sonnenlicht bildet die Haut Vitamin D.', 'Es hilft zum Beispiel den Knochen.'], '#Vitamine #Körper #Sonne #Quiz #Wissen', ph('warm sunlight rays through leaves, golden hour')),
  q('Natur', 'Das Grün der Blätter', 'Welcher Stoff färbt die Blätter grün?', ['Chlorophyll', 'Keratin', 'Insulin'], 0, ['Chlorophyll färbt die Blätter grün.', 'Mit ihm fangen Pflanzen das Sonnenlicht ein.'], '#Pflanzen #Chlorophyll #Natur #Quiz #Wissen', ph('macro of green leaf veins with sunlight')),
  q('Tiere', 'Pflanzenfresser', 'Wie nennt man Tiere, die sich nur von Pflanzen ernähren?', ['Fleischfresser', 'Pflanzenfresser', 'Allesfresser'], 1, ['Tiere, die nur Pflanzen fressen, heißen Pflanzenfresser.', 'Kühe und Pferde gehören dazu.'], '#Tiere #Natur #Biologie #Quiz #Wissen', ph('deer grazing in a green meadow at sunrise')),
  q('Weltall', 'Der Rote Fleck', 'Auf welchem Planeten gibt es den Großen Roten Fleck?', ['Mars', 'Jupiter', 'Saturn'], 1, ['Der Große Rote Fleck ist ein riesiger Sturm auf dem Jupiter.', 'Er wird schon seit Jahrhunderten beobachtet.'], '#Jupiter #Weltall #Planeten #Quiz #Wissen', ph('planet Jupiter with great red spot, cinematic')),
  q('Körper', 'Blut im Körper', 'Wie viel Blut hat ein Erwachsener ungefähr?', ['Etwa 2 Liter', 'Etwa 5 Liter', 'Etwa 10 Liter'], 1, ['Ein Erwachsener hat ungefähr fünf Liter Blut.', 'Das Herz pumpt es ständig durch den Körper.'], '#Blut #Körper #Herz #Quiz #Wissen', ph('abstract red liquid flowing in dark, macro')),
  q('Natur', 'Das härteste Material', 'Welches natürliche Material ist das härteste?', ['Stahl', 'Diamant', 'Quarz'], 1, ['Diamant ist das härteste natürlich vorkommende Material.', 'Er besteht aus reinem Kohlenstoff.'], '#Diamant #Natur #Chemie #Quiz #Wissen', ph('sparkling diamond on dark velvet, dramatic light')),
  q('Geld', 'Preise steigen', 'Wie nennt man es, wenn die Preise über längere Zeit allgemein steigen?', ['Deflation', 'Inflation', 'Rezession'], 1, ['Steigende Preise auf breiter Front nennt man Inflation.', 'Dann kann man für dasselbe Geld weniger kaufen.'], '#Geld #Inflation #Wirtschaft #Quiz #Wissen', ph('coins stacked and a shopping cart silhouette, dramatic light, no people')),
  q('Tiere', 'Das Känguru-Baby', 'Wie heißt ein junges Känguru?', ['Joey', 'Welpe', 'Fohlen'], 0, ['Ein junges Känguru heißt Joey.', 'Es wächst im Beutel der Mutter auf.'], '#Känguru #Tiere #Australien #Quiz #Wissen', ph('kangaroo in the australian outback at sunset')),
  q('Weltall', 'Die Planeten', 'Wie viele Planeten hat unser Sonnensystem?', ['Sieben', 'Acht', 'Neun'], 1, ['Unser Sonnensystem hat acht Planeten.', 'Pluto gilt seit 2006 als Zwergplanet.'], '#Planeten #Weltall #Sonnensystem #Quiz #Wissen', ph('solar system planets lined up in space')),
  q('Natur', 'Was wir ausatmen', 'Welches Gas atmen wir hauptsächlich zusätzlich aus, das wir nicht eingeatmet haben?', ['Helium', 'Kohlendioxid', 'Wasserstoff'], 1, ['Beim Ausatmen geben wir Kohlendioxid ab.', 'Pflanzen nehmen es auf und machen daraus Sauerstoff.'], '#Atmung #Körper #Natur #Quiz #Wissen', ph('mist breath cloud in cold air at dawn, no people')),
  q('Weltall', 'Der Mond mit Atmosphäre', 'Wie heißt der größte Mond des Saturn?', ['Titan', 'Europa', 'Phobos'], 0, ['Titan ist der größte Saturnmond.', 'Er hat als einziger Mond im Sonnensystem eine dichte Atmosphäre.'], '#Saturn #Titan #Weltall #Quiz #Wissen', ph('saturn moon Titan with orange hazy atmosphere in space')),
  q('Weltall', 'Nah an der Sonne', 'Welcher Planet ist der Sonne am nächsten?', ['Venus', 'Merkur', 'Mars'], 1, ['Der Merkur ist der Sonne am nächsten.', 'Trotzdem ist die Venus heißer, wegen ihrer dichten Atmosphäre.'], '#Merkur #Sonne #Weltall #Quiz #Wissen', ph('small grey planet Mercury close to the blazing sun')),
  q('Weltall', 'Sternexplosion', 'Wie nennt man die gewaltige Explosion eines Sterns am Ende seines Lebens?', ['Supernova', 'Quasar', 'Komet'], 0, ['Diese Explosion heißt Supernova.', 'Sie kann kurzzeitig heller leuchten als eine ganze Galaxie.'], '#Supernova #Sterne #Weltall #Quiz #Wissen', ph('supernova explosion with colorful shockwave in deep space')),
  q('Weltall', 'Der Ringplanet', 'Welcher Planet ist für seine riesigen, gut sichtbaren Ringe bekannt?', ['Jupiter', 'Saturn', 'Neptun'], 1, ['Saturn hat die auffälligsten Ringe im Sonnensystem.', 'Sie bestehen aus unzähligen Eis- und Gesteinsbrocken.'], '#Saturn #Ringe #Weltall #Quiz #Wissen', ph('planet Saturn with bright rings, cinematic space view')),
  q('Weltall', 'Eine Runde um die Sonne', 'Wie lange braucht die Erde für eine Runde um die Sonne?', ['Etwa 30 Tage', 'Etwa 365 Tage', 'Etwa 1000 Tage'], 1, ['Die Erde braucht etwa 365 Tage für eine Runde.', 'Weil es genauer 365 und ein Viertel Tage sind, gibt es Schaltjahre.'], '#Erde #Sonne #Weltall #Quiz #Wissen', ph('earth orbiting the sun, wide cinematic space shot')),
  q('Geld', 'Die Währung Japans', 'Wie heißt die Währung von Japan?', ['Yuan', 'Yen', 'Won'], 1, ['In Japan bezahlt man mit dem Yen.', 'Der Yuan ist die Währung Chinas, der Won die Südkoreas.'], '#Geld #Japan #Währung #Quiz #Wissen', ph('japanese yen coins and banknotes on dark table')),
  q('Geld', 'Zinsen auf Zinsen', 'Wie nennt man Zinsen, die auf bereits gutgeschriebene Zinsen gezahlt werden?', ['Dispo', 'Zinseszins', 'Tilgung'], 1, ['Das nennt man Zinseszins.', 'Dadurch wächst ein Betrag mit der Zeit immer schneller.'], '#Geld #Zinsen #Wirtschaft #Quiz #Wissen', ph('growing stacks of coins with soft light, no people')),
  q('Essen', 'Woraus Schokolade ist', 'Aus welcher Pflanze wird Schokolade hergestellt?', ['Kaffee', 'Kakao', 'Vanille'], 1, ['Schokolade wird aus den Bohnen des Kakaobaums gemacht.'], '#Schokolade #Kakao #Essen #Quiz #Wissen', ph('cocoa pods and cocoa beans on a wooden table')),
  q('Essen', 'Popcorn', 'Aus welchem Getreide wird Popcorn gemacht?', ['Weizen', 'Reis', 'Mais'], 2, ['Popcorn ist eine besondere Mais-Sorte.', 'Beim Erhitzen platzt das Wasser im Korn die Schale auf.'], '#Popcorn #Mais #Essen #Quiz #Wissen', ph('popcorn kernels popping in slow motion, warm light')),
];

const MYTHOS = [
  m('Natur', 'Blitze schlagen doppelt ein', 'Blitze schlagen nie zweimal an derselben Stelle ein.', false, ['Das stimmt nicht.', 'Hohe Gebäude und Türme werden sogar mehrmals im Jahr vom Blitz getroffen.'], '#Blitz #Wetter #Natur #Mythos #Wissen', ph('lightning bolt striking over a city skyline at night')),
  m('Essen', 'Honig verdirbt kaum', 'Honig verdirbt praktisch nie.', true, ['Honig enthält sehr wenig Wasser und ist leicht sauer.', 'Bakterien kommen darin kaum zurecht, deshalb hält er extrem lange.'], '#Honig #Essen #Natur #Wahrheit #Wissen', ph('golden honey dripping from a wooden dipper')),
  m('Körper', 'Zehn Prozent vom Gehirn', 'Wir nutzen nur zehn Prozent unseres Gehirns.', false, ['Das ist ein Mythos.', 'Fast alle Bereiche des Gehirns sind aktiv, nur nicht alle gleichzeitig.'], '#Gehirn #Körper #Mythos #Wissen #Psychologie', ph('glowing neural network abstract brain visualization')),
  m('Tiere', 'Das Goldfisch-Gedächtnis', 'Goldfische haben nur ein Gedächtnis von drei Sekunden.', false, ['Das stimmt nicht.', 'Goldfische können sich Wochen bis Monate an Dinge erinnern, zum Beispiel an Futterzeiten.'], '#Goldfisch #Tiere #Mythos #Natur #Wissen', ph('orange goldfish swimming in clear water')),
  m('Natur', 'Die Chinesische Mauer', 'Die Chinesische Mauer ist vom Mond aus mit bloßem Auge zu sehen.', false, ['Das ist ein Mythos.', 'Die Mauer ist zwar sehr lang, aber viel zu schmal, um vom Mond aus erkennbar zu sein.'], '#Mauer #China #Mythos #Weltall #Wissen', ph('ancient great wall winding over green mountains')),
  m('Körper', 'Mehr als fünf Sinne', 'Der Mensch hat mehr als fünf Sinne.', true, ['Neben Sehen, Hören, Riechen, Schmecken und Fühlen gibt es zum Beispiel den Gleichgewichtssinn.', 'Auch Temperatur und Körperlage nehmen wir wahr.'], '#Sinne #Körper #Wahrheit #Wissen #Psychologie', ph('abstract colorful senses concept, eye and ear shapes, no people')),
  m('Natur', 'Bananen und Bäume', 'Bananen wachsen an Bäumen.', false, ['Das stimmt nicht.', 'Bananenpflanzen sind Stauden, keine Bäume. Der Stamm besteht aus fest ineinander liegenden Blättern.'], '#Bananen #Pflanzen #Mythos #Natur #Wissen', ph('banana plant with a large bunch of green bananas')),
  m('Tiere', 'Blinde Fledermäuse', 'Fledermäuse sind blind.', false, ['Das ist ein Mythos.', 'Fledermäuse können sehen und nutzen zusätzlich Ultraschall, um sich im Dunkeln zu orientieren.'], '#Fledermaus #Tiere #Mythos #Natur #Wissen', ph('bat flying at dusk against a purple sky')),
  m('Weltall', 'Die Farbe der Sonne', 'Die Sonne ist in Wahrheit weiß.', true, ['Die Sonne strahlt im ganzen Farbspektrum und wirkt aus dem Weltall weiß.', 'Gelb erscheint sie uns nur durch die Erdatmosphäre.'], '#Sonne #Weltall #Wahrheit #Licht #Wissen', ph('bright white sun with solar flares in space')),
  m('Weltall', 'Venus Tag und Jahr', 'Ein Tag auf der Venus dauert länger als ein Jahr auf der Venus.', true, ['Die Venus dreht sich extrem langsam um sich selbst, für eine Drehung braucht sie etwa 243 Erdtage.', 'Für eine Runde um die Sonne braucht sie nur etwa 225 Erdtage.'], '#Venus #Weltall #Wahrheit #Planeten #Wissen', ph('planet Venus slowly rotating, golden clouds')),
  m('Tiere', 'Strauß und Sand', 'Strauße stecken bei Gefahr den Kopf in den Sand.', false, ['Das ist ein Mythos.', 'Strauße legen den Kopf manchmal an den Boden, um an ihr Nest zu kommen, oder rennen bei Gefahr einfach davon.'], '#Strauß #Tiere #Mythos #Natur #Wissen', ph('ostrich walking in an african savanna at sunset')),
  m('Körper', 'Fingerabdrücke bei Zwillingen', 'Selbst eineiige Zwillinge haben unterschiedliche Fingerabdrücke.', true, ['Fingerabdrücke entstehen schon im Mutterleib und werden auch durch Zufälle geformt.', 'Deshalb sind sie bei jedem Menschen einzigartig.'], '#Fingerabdruck #Zwillinge #Körper #Wahrheit #Wissen', ph('macro of a fingerprint pattern glowing, abstract')),
  m('Weltall', 'Der Mond entfernt sich', 'Der Mond entfernt sich jedes Jahr ein paar Zentimeter von der Erde.', true, ['Der Mond wandert pro Jahr etwa knapp vier Zentimeter weiter weg.', 'Das haben Messungen mit Laserstrahlen gezeigt.'], '#Mond #Weltall #Wahrheit #Erde #Wissen', ph('moon rising behind the earth horizon from space')),
  m('Körper', 'Haare nach dem Tod', 'Haare und Fingernägel wachsen nach dem Tod weiter.', false, ['Das ist ein Mythos.', 'Die Haut zieht sich zurück und trocknet aus, dadurch wirken Haare und Nägel länger.'], '#Körper #Haare #Mythos #Wissen #Anatomie', ph('abstract dark macro texture of hair strands')),
  m('Essen', 'Zucker und Hyperaktivität', 'Zucker macht Kinder hyperaktiv.', false, ['Das haben viele Studien nicht bestätigt.', 'Wahrscheinlich liegt es eher an der Aufregung auf Partys, nicht am Zucker.'], '#Zucker #Essen #Mythos #Wissen #Kinder', ph('colorful candy pile, studio light')),
  m('Körper', 'Kaugummi im Magen', 'Verschluckter Kaugummi bleibt sieben Jahre im Magen.', false, ['Das ist ein Mythos.', 'Der Körper scheidet Kaugummi nach einigen Tagen auf normalem Weg wieder aus.'], '#Kaugummi #Körper #Mythos #Wissen #Gesundheit', ph('pink bubble gum bubble on a dark background')),
  m('Tiere', 'Stiere sehen rot', 'Stiere werden wütend, wenn sie die Farbe Rot sehen.', false, ['Das ist ein Mythos.', 'Stiere können Rot nicht gut von anderen Farben unterscheiden.', 'Sie reagieren auf die Bewegung des Tuchs.'], '#Stier #Tiere #Mythos #Natur #Wissen', ph('bull standing in a field at golden hour')),
  m('Natur', 'Warum es Sommer wird', 'Es ist Sommer, weil die Erde der Sonne dann näher ist.', false, ['Das stimmt nicht.', 'Die Jahreszeiten entstehen, weil die Erdachse schräg steht.', 'Im Sommer der Nordhalbkugel ist die Erde sogar weiter von der Sonne entfernt.'], '#Sommer #Erde #Mythos #Wissen #Natur', ph('summer sun over a green field with blue sky')),
  m('Körper', 'Fingerknacken', 'Fingerknacken führt zu Arthrose.', false, ['Das haben Studien nicht bestätigt.', 'Das Knacken entsteht durch Gasblasen in der Gelenkflüssigkeit.'], '#Körper #Gelenke #Mythos #Wissen #Gesundheit', ph('abstract x ray style hand bones glowing blue')),
  m('Tiere', 'Wasser im Kamelhöcker', 'Kamele speichern Wasser in ihren Höckern.', false, ['Das ist ein Mythos.', 'In den Höckern speichern Kamele Fett als Energiereserve.'], '#Kamel #Tiere #Mythos #Wüste #Wissen', ph('camel walking in the desert at sunset')),
  m('Essen', 'Karotten und Nachtsicht', 'Karotten geben dir eine super Nachtsicht.', false, ['Das ist stark übertrieben.', 'Das enthaltene Vitamin A ist gut für die Augen, macht aber keine Nachtsicht-Superkraft.'], '#Karotten #Essen #Mythos #Augen #Wissen', ph('fresh orange carrots on a dark wooden table')),
  m('Weltall', 'Ton im Weltall', 'Im Weltall kann man keinen Ton hören.', true, ['Schall braucht Luft oder ein anderes Material, um sich auszubreiten.', 'Im luftleeren Raum gibt es nichts, was ihn weitertragen könnte.'], '#Weltall #Physik #Wahrheit #Wissen #Schall', ph('silent astronaut helmet reflection of stars, no people')),
  m('Natur', 'Reines Wasser und Strom', 'Reines Wasser leitet Strom besonders gut.', false, ['Das stimmt nicht.', 'Reines Wasser leitet kaum Strom.', 'Erst gelöste Stoffe wie Salze machen es leitfähig.'], '#Wasser #Physik #Mythos #Wissen #Strom', ph('clear water drop splash macro, dark background')),
  m('Körper', 'Wärme über den Kopf', 'Wir verlieren die meiste Körperwärme über den Kopf.', false, ['Das ist ein Mythos.', 'Der Kopf verliert nur im Verhältnis zu seiner Fläche Wärme.', 'Auch über Arme und Beine geht viel Wärme verloren.'], '#Körper #Wärme #Mythos #Wissen #Winter', ph('winter landscape with snow and warm light, no people')),
  m('Tiere', 'Delfine sind Säugetiere', 'Delfine sind Säugetiere und keine Fische.', true, ['Delfine atmen Luft und säugen ihre Jungen mit Milch.', 'Das sind typische Merkmale von Säugetieren.'], '#Delfine #Tiere #Wahrheit #Natur #Wissen', ph('dolphin jumping out of the ocean at sunset')),
  m('Natur', 'Diamanten aus Kohle', 'Diamanten entstehen aus Kohle.', false, ['Das ist ein Mythos.', 'Diamanten bilden sich tief im Erdmantel aus Kohlenstoff, meist viel tiefer, als Kohle vorkommt.'], '#Diamant #Natur #Mythos #Wissen #Erde', ph('rough uncut diamond crystals on dark rock')),
  m('Weltall', 'Schwarze Löcher saugen', 'Schwarze Löcher saugen alles in ihrer Nähe auf wie ein Staubsauger.', false, ['Das ist ein Mythos.', 'Aus der Ferne wirkt ihre Schwerkraft wie die eines normalen Sterns mit gleicher Masse.', 'Nur wer sehr nah herankommt, wird verschluckt.'], '#SchwarzesLoch #Weltall #Mythos #Wissen #Physik', ph('black hole with glowing accretion disk in space')),
  m('Körper', 'Gehirn und Wasser', 'Das menschliche Gehirn besteht zum größten Teil aus Wasser.', true, ['Rund drei Viertel des Gehirns bestehen aus Wasser.', 'Schon wenig Flüssigkeitsmangel kann die Konzentration senken.'], '#Gehirn #Körper #Wahrheit #Wissen #Wasser', ph('glowing abstract brain with neural lights')),
  m('Tiere', 'Haie und Schwimmen', 'Alle Haie ersticken, wenn sie aufhören zu schwimmen.', false, ['Das stimmt nicht.', 'Manche Haie können Wasser über die Kiemen pumpen und ruhen am Boden.'], '#Haie #Tiere #Mythos #Ozean #Wissen', ph('shark swimming in deep blue ocean')),
  m('Essen', 'Tomaten sind Beeren', 'Botanisch gesehen ist die Tomate eine Beere.', true, ['Botanisch zählt die Tomate zu den Beeren.', 'Im Alltag nennen wir sie trotzdem Gemüse.'], '#Tomaten #Essen #Wahrheit #Botanik #Wissen', ph('fresh red tomatoes with water drops, dark background')),
  m('Tiere', 'Wale sind Fische', 'Wale sind Fische.', false, ['Das ist ein Mythos.', 'Wale sind Säugetiere, sie atmen Luft und säugen ihre Jungen.'], '#Wale #Tiere #Mythos #Ozean #Wissen', ph('whale tail above deep blue ocean at sunset')),
  m('Geld', 'Euro-Scheine aus Baumwolle', 'Euro-Banknoten bestehen nicht aus normalem Papier, sondern aus Baumwolle.', true, ['Euro-Scheine bestehen aus Baumwollfasern.', 'Das macht sie besonders reißfest.'], '#Geld #Euro #Wahrheit #Wissen #Banknoten', ph('euro banknotes fanned out on dark table, macro')),
  m('Körper', 'Blaues Blut', 'Unser Blut in den Venen ist blau.', false, ['Das ist ein Mythos.', 'Blut ist immer rot, mit Sauerstoff etwas heller, ohne etwas dunkler.', 'Venen wirken durch die Haut nur bläulich.'], '#Blut #Körper #Mythos #Wissen #Anatomie', ph('abstract blue and red flowing lines like veins, dark')),
  m('Weltall', 'Jupiter hat keine Oberfläche', 'Auf dem Jupiter kann man nicht stehen, weil er keine feste Oberfläche hat.', true, ['Jupiter ist ein Gasriese und besteht vor allem aus Wasserstoff und Helium.', 'Nach innen wird das Gas immer dichter.'], '#Jupiter #Weltall #Wahrheit #Planeten #Wissen', ph('planet Jupiter swirling clouds close up')),
  m('Natur', 'Bambus ist ein Gras', 'Bambus ist botanisch ein Gras.', true, ['Bambus gehört zur Familie der Süßgräser.', 'Manche Arten wachsen an einem Tag fast einen Meter.'], '#Bambus #Pflanzen #Wahrheit #Natur #Wissen', ph('tall bamboo forest with sunlight beams')),
  m('Weltall', 'Warum Sterne funkeln', 'Das Funkeln der Sterne entsteht in unserer eigenen Atmosphäre.', true, ['Die Luft über uns ist ständig in Bewegung und lenkt das Sternenlicht ab.', 'Im Weltall würden die Sterne ruhig leuchten.'], '#Sterne #Weltall #Wahrheit #Himmel #Wissen', ph('starry night sky with twinkling stars over mountains')),
  m('Weltall', 'Die dunkle Seite des Mondes', 'Die Rückseite des Mondes ist immer dunkel.', false, ['Das ist ein Mythos.', 'Die Rückseite bekommt genauso Sonnenlicht, wir sehen sie von der Erde nur nie.'], '#Mond #Weltall #Mythos #Wissen #Himmel', ph('far side of the moon lit by sunlight in space')),
  m('Weltall', 'Kein Wind auf dem Mond', 'Auf dem Mond weht kein Wind.', true, ['Der Mond hat fast keine Atmosphäre.', 'Ohne Luft gibt es auch keinen Wind.'], '#Mond #Weltall #Wahrheit #Wissen #Raumfahrt', ph('still grey lunar surface with craters and black sky')),
  m('Weltall', 'Die Monde des Mars', 'Der Mars hat zwei kleine Monde.', true, ['Die beiden Marsmonde heißen Phobos und Deimos.', 'Sie sind viel kleiner als unser Mond.'], '#Mars #Weltall #Wahrheit #Monde #Wissen', ph('mars with two tiny moons in space, cinematic')),
  m('Weltall', 'Sternschnuppen', 'Sternschnuppen sind herabfallende Sterne.', false, ['Das ist ein Mythos.', 'Sternschnuppen sind winzige Staub- und Gesteinsteilchen, die in der Atmosphäre verglühen.'], '#Sternschnuppe #Weltall #Mythos #Himmel #Wissen', ph('shooting stars streaking across night sky over a lake')),
  m('Geld', 'Euro als Bargeld', 'Der Euro ist erst seit 2002 als Bargeld im Umlauf.', true, ['Als Buchgeld gab es den Euro schon ab 1999.', 'Münzen und Scheine kamen am 1. Januar 2002.'], '#Geld #Euro #Wahrheit #Geschichte #Wissen', ph('new euro coins shining on dark surface, macro')),
  m('Geld', 'Uralte Münzen', 'Münzgeld gibt es schon seit über 2500 Jahren.', true, ['Die ersten Münzen wurden vor mehr als 2500 Jahren in Kleinasien geprägt.'], '#Geld #Münzen #Wahrheit #Geschichte #Wissen', ph('ancient gold coins in an old museum display, no people')),
  m('Essen', 'Erdnüsse sind keine Nüsse', 'Erdnüsse sind botanisch gar keine Nüsse.', true, ['Erdnüsse gehören zu den Hülsenfrüchten, wie Erbsen und Bohnen.', 'Sie reifen unter der Erde.'], '#Erdnuss #Essen #Wahrheit #Botanik #Wissen', ph('peanuts in their shells on a rustic table')),
  m('Essen', 'Weiße Schokolade', 'Weiße Schokolade enthält Kakaobutter, aber keine Kakaomasse.', true, ['Weiße Schokolade besteht vor allem aus Kakaobutter, Zucker und Milch.', 'Die dunkle Kakaomasse fehlt, deshalb ist sie hell.'], '#Schokolade #Essen #Wahrheit #Süßes #Wissen', ph('white chocolate pieces on dark background, studio light')),
];

// Abwechselnd Quiz und Mythos - so wiederholt sich das Format nicht.
export const BANK = Array.from({ length: Math.max(QUIZ.length, MYTHOS.length) }, (_, i) => [QUIZ[i], MYTHOS[i]]).flat().filter(Boolean).map((e, i) => ({ ...e, id: `b${i + 1}` }));

// Naechster noch nicht benutzter Eintrag (verwendet = Liste benutzter ids), sonst null.
// Mit kats (Nische eines Kontos) zuerst ein Eintrag aus diesen Kategorien, mit typ (gelerntes Lieblingsformat)
// darin zuerst dieses Format; sonst irgendeiner.
export function bankNaechster(verwendet = [], kats = [], typ = null) {
  const frei = BANK.filter((e) => !verwendet.includes(e.id));
  const inNische = kats.length ? frei.filter((e) => kats.includes(e.kat)) : frei;
  return (typ && inNische.find((e) => e.typ === typ)) || inNische[0] || frei[0] || null;
}
